repos:
  - repo: local
    hooks:
      - id: cljfmt
        name: cljfmt
        language: script
        entry: bin/cljfmt-and-restage
        types: [clojure]
        pass_filenames: true

      - id: clj-kondo
        name: clj-kondo
        language: system
        entry: clj-kondo --lint
        types: [clojure]
        pass_filenames: true
