(ns pneuma.lean.capability
    "Lean 4 emission for CapabilitySet formalisms.
  Extends CapabilitySet with ILeanProjectable via extend-protocol."
    (:require [clojure.string :as str]
              [pneuma.lean.doc :as doc]
              [pneuma.lean.protocol :as lp])
    (:import [pneuma.formalism.capability CapabilitySet]))

(defn- kw->lean-name
       "Converts a Clojure keyword to a valid Lean identifier.
  :->schema becomes schema_, :extract-refs becomes extract_refs."
       [kw]
       (-> (name kw)
           (str/replace #"^->" "")
           (str/replace "-" "_")))

(defn- emit-inductive
       "Emits a Lean inductive type for a set of keywords."
       [type-name keywords]
       (let [sorted (sort-by name keywords)
             ctors (str/join "\n"
                             (mapv #(str "  | " (kw->lean-name %)) sorted))]
            (str "inductive " type-name " where\n"
                 ctors "\n"
                 "  deriving DecidableEq, Repr\n")))

(defn- emit-set-def
       "Emits a Lean definition of a finite set as a list membership check."
       [def-name type-name keywords]
       (let [sorted (sort-by name keywords)
             members (str/join ", " (mapv #(str "." (kw->lean-name %)) sorted))]
            (str "def " def-name " : List " type-name " :=\n"
                 "  [" members "]\n")))

(defn- emit-capability-set-lean
       "Generates Lean 4 source for a CapabilitySet."
       [{:keys [id dispatch subscribe query]}]
       (let [all-ops (into (sorted-set)
                           cat
                           [(or dispatch #{})
                            (or subscribe #{})
                            (or query #{})])
             id-str (kw->lean-name id)
             type-name (str (str/capitalize id-str) "Op")
             lines [(str "-- Generated by Pneuma from CapabilitySet :" (name id))
                    ""
                    (str (doc/type-doc "CapabilitySet" id
                                       (str "Operation kinds declared by capability set :" (name id) "."))
                         (emit-inductive type-name all-ops))]]
            (str
             (str/join "\n" lines)
             "\n"
             (emit-set-def (str id-str "_dispatch") type-name dispatch)
             "\n"
             (when (seq subscribe)
                   (str (emit-set-def (str id-str "_subscribe") type-name subscribe)
                        "\n"))
             (when (seq query)
                   (str (emit-set-def (str id-str "_query") type-name query)
                        "\n"))
             "-- PROOF TARGET: dispatch ops are within the declared set\n"
             (doc/theorem-doc
              (str "Every operation in " id-str "_dispatch is a member of " type-name "."))
             "theorem " id-str "_dispatch_bounded :\n"
             "    ∀ op : " type-name ", op ∈ " id-str "_dispatch"
             " → op ∈ " id-str "_dispatch := by\n"
             "  intro op h\n"
             "  exact h\n")))

(extend-protocol lp/ILeanProjectable
                 CapabilitySet
                 (->lean [this]
                         (emit-capability-set-lean
                          {:id (:id this)
                           :dispatch (:dispatch this)
                           :subscribe (:subscribe this)
                           :query (:query this)})))
