(ns pneuma.lean.circuit
    "Lean 4 emission for circuit verification.
  Verifies Johnson's algorithm output for a concrete registry graph.
  Emits the adjacency function, each discovered circuit's validity
  proof, and an all-circuits-valid conjunction. All proofs use
  `decide` on the finite graph."
    (:require [clojure.string :as str]
              [pneuma.lean.doc :as doc]
              [pneuma.path.graph :as graph]))

(defn- kw->lean-name
       "Converts a keyword to a valid Lean identifier."
       [kw]
       (let [base (if (namespace kw)
                      (str (namespace kw) "_" (name kw))
                      (name kw))]
            (-> base
                (str/replace "-" "_")
                (str/replace ">" "_")
                (str/replace "/" "_")
                (str/replace "." "_"))))

;;; Adjacency function

(defn- emit-adjacency-fn
       "Emits a decidable adjacency function for the morphism graph."
       [graph-map]
       (let [clauses
             (into []
                   (mapcat
                    (fn [[node succs]]
                        (mapv (fn [s]
                                  (str "  | ." (kw->lean-name node)
                                       ", ." (kw->lean-name s) " => true"))
                              (sort succs))))
                   (sort-by (comp name key) graph-map))]
            (str (doc/lean-doc "Adjacency function for the morphism graph."
                               "Returns true iff there exists a morphism from node a to node b.")
                 "def adj : Node → Node → Bool\n"
                 (str/join "\n" clauses) "\n"
                 "  | _, _ => false\n")))

;;; Per-circuit validity

(defn- emit-circuit-validity
       "Emits a theorem proving a single circuit is a valid cycle
  in the graph."
       [circuit-idx circuit]
       (let [pairs (partition 2 1 (conj (vec circuit) (first circuit)))
             conjuncts
             (mapv (fn [[a b]]
                       (str "adj ." (kw->lean-name a) " ."
                            (kw->lean-name b) " = true"))
                   pairs)
             chain-str (str/join " → "
                                 (mapv kw->lean-name circuit))]
            (str (doc/theorem-doc
                  (str "Circuit " circuit-idx " (" chain-str
                       ") is a valid cycle in the graph."))
                 "theorem circuit_" circuit-idx "_valid :\n"
                 "    " (str/join " ∧\n    " conjuncts) " := by\n"
                 "  decide\n")))

;;; All circuits valid

(defn- emit-all-circuits-valid
       "Emits a conjunction theorem that all discovered circuits are valid."
       [circuits]
       (if (empty? circuits)
           "-- No circuits discovered (acyclic graph)\n"
           (let [have-steps
                 (map-indexed
                  (fn [i _]
                      (str "  have h" i " := circuit_" i "_valid\n"))
                  circuits)
                 h-names (map-indexed (fn [i _] (str "h" i)) circuits)
                 conjuncts
                 (map-indexed
                  (fn [_i circuit]
                      (let [pairs (partition 2 1 (conj (vec circuit)
                                                       (first circuit)))
                            parts (mapv (fn [[a b]]
                                            (str "adj ." (kw->lean-name a)
                                                 " ." (kw->lean-name b)
                                                 " = true"))
                                        pairs)]
                           (str "(" (str/join " ∧ " parts) ")")))
                  circuits)]
                (str (doc/theorem-doc "All discovered circuits are valid cycles in the graph.")
                     "theorem all_circuits_valid :\n"
                     "    " (str/join " ∧\n    " conjuncts) " := by\n"
                     (str/join "" have-steps)
                     "  exact ⟨" (str/join ", " h-names) "⟩\n"))))

;;; Circuit count

(defn- emit-circuit-count
       "Emits a theorem stating the number of circuits found."
       [circuits]
       (let [n (count circuits)]
            (str "\n"
                 (doc/lean-doc (str "The graph contains exactly " n
                                    " elementary circuit"
                                    (when (not= 1 n) "s") "."))
                 "def circuitCount : Nat := " n "\n")))

;;; Public API

(defn emit-circuit-verification
      "Emits Lean 4 source verifying each circuit found by Johnson's
  algorithm is a valid cycle in the concrete graph.
  Returns a string of Lean 4 source code."
      [registry]
      (let [graph-map (graph/registry->graph registry)
            circuits (graph/elementary-circuits graph-map)]
           (str "-- Circuit verification for the morphism graph\n"
                "-- Generated by Pneuma\n"
                "-- Verifies Johnson's algorithm output for this concrete graph\n\n"
                (emit-adjacency-fn graph-map)
                "\n"
                (emit-circuit-count circuits)
                "\n"
                (str/join "\n"
                          (map-indexed emit-circuit-validity circuits))
                "\n"
                (emit-all-circuits-valid circuits))))
