(ns pneuma.lean.containment
    "Lean 4 emission for ContainmentMorphism boundaries.
  Extends ContainmentMorphism with ILeanConnection via extend-protocol.
  Emits inductive types for source and target reference sets and a subset
  proposition: every source ref is a member of the target set."
    (:require [clojure.string :as str]
              [pneuma.lean.doc :as doc]
              [pneuma.lean.protocol :as lp]
              [pneuma.protocol :as p])
    (:import [pneuma.morphism.containment ContainmentMorphism]))

(defn- kw->lean-name
       "Converts a keyword to a valid Lean identifier."
       [kw]
       (let [base (if (namespace kw)
                      (str (namespace kw) "_" (name kw))
                      (name kw))]
            (-> base
                (str/replace "-" "_")
                (str/replace ">" "_")
                (str/replace "/" "_")
                (str/replace "." "_"))))

(defn- morphism-id->lean-prefix
       "Converts a morphism id keyword to a CamelCase Lean prefix."
       [id-kw]
       (let [raw (kw->lean-name id-kw)]
            (->> (str/split raw #"_")
                 (mapv str/capitalize)
                 (str/join ""))))

(defn- emit-inductive
       "Emits a Lean inductive type from a set of keywords."
       [type-name refs]
       (let [sorted (sort (mapv kw->lean-name refs))
             ctors (str/join "\n"
                             (mapv #(str "  | " %) sorted))]
            (str "inductive " type-name " where\n"
                 ctors "\n"
                 "  deriving DecidableEq, Repr\n")))

(defn- emit-all-list
       "Emits an allXxx list and completeness theorem."
       [type-name refs]
       (let [sorted (sort (mapv kw->lean-name refs))
             members (str/join ", " (mapv #(str "." %) sorted))]
            (str "def all" type-name " : List " type-name " :=\n"
                 "  [" members "]\n"
                 "\ntheorem all" type-name "_complete :\n"
                 "    ∀ x : " type-name ", x ∈ all" type-name " := by\n"
                 "  intro x\n"
                 "  cases x <;> simp [all" type-name "]\n")))

(defn- emit-membership-fn
       "Emits a function checking whether a source ref is a member of the
  target set, returning a Bool."
       [prefix source-refs target-refs]
       (let [target-names (into #{} (map kw->lean-name) target-refs)
             sorted-sources (sort (mapv kw->lean-name source-refs))
             clauses (str/join "\n"
                               (mapv (fn [sname]
                                         (if (target-names sname)
                                             (str "  | ." sname " => true")
                                             (str "  | ." sname " => false")))
                                     sorted-sources))]
            (str "def " prefix "InTarget : " prefix "Source → Bool\n"
                 clauses "\n")))

(defn- emit-boundary-proposition
       "Emits the containment boundary proposition: every source ref is a
  member of the target set."
       [id prefix]
       (str "-- PROOF TARGET: every source reference is contained in the target set\n"
            (doc/morphism-theorem-doc "ContainmentMorphism" id
                                      "Every source reference is contained in the target set.")
            "theorem " prefix "_containment_boundary :\n"
            "    ∀ s : " prefix "Source, " prefix "InTarget s = true := by\n"
            "  intro s\n"
            "  cases s <;> rfl\n"))

(defn- emit-containment-lean
       "Generates Lean 4 source for a ContainmentMorphism boundary."
       [{:keys [id from to source-ref-kind target-ref-kind]}
        source-refs target-refs]
       (let [prefix (morphism-id->lean-prefix id)]
            (str "-- Generated by Pneuma from ContainmentMorphism " id "\n"
                 "-- Boundary: " (name from) " → " (name to) "\n"
                 "-- Source ref-kind: " (name source-ref-kind)
                 ", Target ref-kind: " (name target-ref-kind) "\n\n"
                 (doc/morphism-type-doc "ContainmentMorphism" id
                                        (str "Source references for containment check " (name from) " → " (name to) "."))
                 (emit-inductive (str prefix "Source") source-refs)
                 "\n"
                 (doc/morphism-type-doc "ContainmentMorphism" id
                                        (str "Target references for containment check " (name from) " → " (name to) "."))
                 (emit-inductive (str prefix "Target") target-refs)
                 "\n"
                 (emit-all-list (str prefix "Source") source-refs)
                 "\n"
                 (emit-all-list (str prefix "Target") target-refs)
                 "\n"
                 (doc/lean-doc "Checks whether each source reference exists in the target set.")
                 (emit-membership-fn prefix source-refs target-refs)
                 "\n"
                 (emit-boundary-proposition id prefix))))

(extend-protocol lp/ILeanConnection
                 ContainmentMorphism
                 (->lean-conn [this source target]
                              (let [source-refs (p/extract-refs source
                                                                (:source-ref-kind this))
                                    target-refs (p/extract-refs target
                                                                (:target-ref-kind this))]
                                   (emit-containment-lean
                                    this source-refs target-refs))))
