(ns pneuma.lean.mealy
    "Lean 4 emission for MealyHandlerSet formalisms.
  Extends MealyHandlerSet with ILeanProjectable via extend-protocol.
  Emits inductive HandlerId type, handler count, and completeness."
    (:require [clojure.string :as str]
              [pneuma.lean.protocol :as lp])
    (:import [pneuma.formalism.mealy MealyHandlerSet]))

(defn- kw->lean-name
       [kw]
       (-> (name kw)
           (str/replace "-" "_")
           (str/replace "/" "_")))

(defn- emit-handler-inductive
       [handler-ids]
       (let [sorted (sort (mapv kw->lean-name handler-ids))
             ctors (str/join "\n"
                             (mapv #(str "  | " %) sorted))]
            (str "inductive HandlerId where\n"
                 ctors "\n"
                 "  deriving DecidableEq, Repr\n")))

(defn- emit-guard-refs
       "Emits the set of state refs from guards as a list."
       [declarations]
       (let [all-guard-states
             (into (sorted-set)
                   (mapcat (fn [decl]
                               (keep (fn [guard]
                                         (when (= :in-state? (:check guard))
                                               (kw->lean-name (second (:args guard)))))
                                     (:guards decl []))))
                   (vals declarations))]
            (when (seq all-guard-states)
                  (let [members (str/join ", "
                                          (mapv #(str "\"" % "\"") all-guard-states))]
                       (str "def guardStateRefs : List String :=\n"
                            "  [" members "]\n\n")))))

(defn- emit-emission-refs
       "Emits the set of effect operation refs as a list."
       [declarations]
       (let [all-ops (into (sorted-set)
                           (mapcat (fn [decl]
                                       (mapv (comp kw->lean-name :op)
                                             (:effects decl []))))
                           (vals declarations))]
            (when (seq all-ops)
                  (let [members (str/join ", "
                                          (mapv #(str "\"" % "\"") all-ops))]
                       (str "def emissionOpRefs : List String :=\n"
                            "  [" members "]\n\n")))))

(defn- emit-completeness
       [handler-ids]
       (let [sorted (sort (mapv kw->lean-name handler-ids))
             members (str/join ", " (mapv #(str "." %) sorted))
             n (count handler-ids)]
            (str "\ndef allHandlers : List HandlerId :=\n"
                 "  [" members "]\n"
                 "\ntheorem allHandlers_complete :\n"
                 "    ∀ h : HandlerId, h ∈ allHandlers := by\n"
                 "  intro h\n"
                 "  cases h <;> simp [allHandlers]\n"
                 "\ntheorem allHandlers_count :\n"
                 "    allHandlers.length = " n " := by\n"
                 "  rfl\n")))

(defn- emit-mealy-lean
       [declarations]
       (let [handler-ids (keys declarations)]
            (str "-- Generated by Pneuma from MealyHandlerSet\n\n"
                 (emit-handler-inductive handler-ids)
                 (emit-completeness handler-ids)
                 "\n"
                 (or (emit-guard-refs declarations) "")
                 (or (emit-emission-refs declarations) ""))))

(extend-protocol lp/ILeanProjectable
                 MealyHandlerSet
                 (->lean [this]
                         (emit-mealy-lean (:declarations this))))
