(ns pneuma.lean.mealy
    "Lean 4 emission for MealyHandlerSet formalisms.
  Extends MealyHandlerSet with ILeanProjectable via extend-protocol.
  Emits inductive HandlerId type, handler count, and completeness."
    (:require [clojure.string :as str]
              [pneuma.lean.doc :as doc]
              [pneuma.lean.protocol :as lp])
    (:import [pneuma.formalism.mealy MealyHandlerSet]))

(defn- kw->lean-name
       [kw]
       (-> (name kw)
           (str/replace "-" "_")
           (str/replace "/" "_")))

(defn- emit-handler-inductive
       [handler-ids]
       (let [sorted (sort (mapv kw->lean-name handler-ids))
             ctors (str/join "\n"
                             (mapv #(str "  | " %) sorted))]
            (str "inductive HandlerId where\n"
                 ctors "\n"
                 "  deriving DecidableEq, Repr\n")))

(defn- emit-guard-refs
       "Emits the set of state refs from guards as a list."
       [id declarations]
       (let [all-guard-states
             (into (sorted-set)
                   (mapcat (fn [decl]
                               (keep (fn [guard]
                                         (when (= :in-state? (:check guard))
                                               (kw->lean-name (second (:args guard)))))
                                     (:guards decl []))))
                   (vals declarations))]
            (when (seq all-guard-states)
                  (let [members (str/join ", "
                                          (mapv #(str "\"" % "\"") all-guard-states))]
                       (str (doc/lean-doc (str "State references checked by guards in MealyHandlerSet"
                                               (when id (str " " (doc/id-str id))) "."))
                            "def guardStateRefs : List String :=\n"
                            "  [" members "]\n\n")))))

(defn- emit-emission-refs
       "Emits the set of effect operation refs as a list."
       [id declarations]
       (let [all-ops (into (sorted-set)
                           (mapcat (fn [decl]
                                       (mapv (comp kw->lean-name :op)
                                             (:effects decl []))))
                           (vals declarations))]
            (when (seq all-ops)
                  (let [members (str/join ", "
                                          (mapv #(str "\"" % "\"") all-ops))]
                       (str (doc/lean-doc (str "Effect operations emitted by handlers in MealyHandlerSet"
                                               (when id (str " " (doc/id-str id))) "."))
                            "def emissionOpRefs : List String :=\n"
                            "  [" members "]\n\n")))))

(defn- emit-completeness
       [id handler-ids]
       (let [sorted (sort (mapv kw->lean-name handler-ids))
             members (str/join ", " (mapv #(str "." %) sorted))
             n (count handler-ids)]
            (str "\n"
                 (doc/lean-doc (str "Exhaustive list of all handlers in MealyHandlerSet"
                                    (when id (str " " (doc/id-str id))) "."))
                 "def allHandlers : List HandlerId :=\n"
                 "  [" members "]\n"
                 "\n"
                 (doc/theorem-doc "Every member of HandlerId appears in allHandlers. Proved by case analysis.")
                 "theorem allHandlers_complete :\n"
                 "    ∀ h : HandlerId, h ∈ allHandlers := by\n"
                 "  intro h\n"
                 "  cases h <;> simp [allHandlers]\n"
                 "\n"
                 (doc/theorem-doc (str "allHandlers contains exactly " n " members."))
                 "theorem allHandlers_count :\n"
                 "    allHandlers.length = " n " := by\n"
                 "  rfl\n")))

(defn- emit-mealy-lean
       [id declarations]
       (let [handler-ids (keys declarations)
             id-label (if id (str " " (doc/id-str id)) "")]
            (str "-- Generated by Pneuma from MealyHandlerSet" id-label "\n\n"
                 (doc/type-doc "MealyHandlerSet" id
                               (str "Handler identifiers for MealyHandlerSet" id-label "."))
                 (emit-handler-inductive handler-ids)
                 (emit-completeness id handler-ids)
                 "\n"
                 (or (emit-guard-refs id declarations) "")
                 (or (emit-emission-refs id declarations) ""))))

(extend-protocol lp/ILeanProjectable
                 MealyHandlerSet
                 (->lean [this]
                         (emit-mealy-lean (:id this) (:declarations this))))
