(ns pneuma.lean.ordering
    "Lean 4 emission for OrderingMorphism boundaries.
  Extends OrderingMorphism with ILeanConnection via extend-protocol.
  Emits an inductive type for the chain, an index function mapping each
  element to its Nat position, and the ordering proposition: source index
  < target index, proved by decide."
    (:require [clojure.string :as str]
              [pneuma.lean.protocol :as lp]
              [pneuma.protocol :as p])
    (:import [pneuma.morphism.ordering OrderingMorphism]))

(defn- kw->lean-name
       "Converts a keyword to a valid Lean identifier."
       [kw]
       (let [base (if (namespace kw)
                      (str (namespace kw) "_" (name kw))
                      (name kw))]
            (-> base
                (str/replace "-" "_")
                (str/replace ">" "_")
                (str/replace "/" "_")
                (str/replace "." "_"))))

(defn- morphism-id->lean-prefix
       "Converts a morphism id keyword to a CamelCase Lean prefix."
       [id-kw]
       (let [raw (kw->lean-name id-kw)]
            (->> (str/split raw #"_")
                 (mapv str/capitalize)
                 (str/join ""))))

(defn- emit-chain-inductive
       "Emits a Lean inductive type with one constructor per chain element."
       [type-name chain]
       (let [ctors (str/join "\n"
                             (mapv #(str "  | " (kw->lean-name %)) chain))]
            (str "inductive " type-name " where\n"
                 ctors "\n"
                 "  deriving DecidableEq, Repr\n")))

(defn- emit-index-fn
       "Emits a Nat-valued index function mapping each chain element to its position."
       [prefix type-name chain]
       (let [clauses (str/join "\n"
                               (map-indexed
                                (fn [i kw]
                                    (str "  | ." (kw->lean-name kw) " => " i))
                                chain))]
            (str "def " prefix "ChainIndex : " type-name " → Nat\n"
                 clauses "\n")))

(defn- emit-ordering-proposition
       "Emits the ordering proposition: source index < target index, proved by decide."
       [prefix source-ref target-ref]
       (let [src-name (kw->lean-name source-ref)
             tgt-name (kw->lean-name target-ref)]
            (str "-- PROOF TARGET: source precedes target in the chain\n"
                 "theorem " prefix "_ordering_boundary :\n"
                 "    " prefix "ChainIndex ." src-name " < "
                 prefix "ChainIndex ." tgt-name " := by\n"
                 "  decide\n")))

(defn- emit-ordering-lean
       "Generates Lean 4 source for an OrderingMorphism boundary."
       [{:keys [id from to source-ref-kind target-ref-kind chain]}
        source-ref target-ref]
       (let [prefix    (morphism-id->lean-prefix id)
             type-name (str prefix "Chain")]
            (str "-- Generated by Pneuma from OrderingMorphism " id "\n"
                 "-- Boundary: " (name from) " → " (name to) "\n"
                 "-- Source ref-kind: " (name source-ref-kind)
                 ", Target ref-kind: " (name target-ref-kind) "\n\n"
                 (emit-chain-inductive type-name chain)
                 "\n"
                 (emit-index-fn prefix type-name chain)
                 "\n"
                 (emit-ordering-proposition prefix source-ref target-ref))))

(extend-protocol lp/ILeanConnection
                 OrderingMorphism
                 (->lean-conn [this source target]
                              (let [source-ref (first (p/extract-refs source
                                                                      (:source-ref-kind this)))
                                    target-ref (first (p/extract-refs target
                                                                      (:target-ref-kind this)))]
                                   (emit-ordering-lean this source-ref target-ref))))
