(ns pneuma.lean.ref-exhaustive
    "Lean 4 emission for ref-extraction exhaustiveness.
  For each formalism, proves that extract-refs covers all ref-kinds
  used in the registry. Emits RefKind inductives per formalism and
  exhaustiveness theorems proved by case analysis."
    (:require [clojure.string :as str]
              [pneuma.lean.doc :as doc]))

(defn- kw->lean-name
       "Converts a keyword to a valid Lean identifier."
       [kw]
       (let [base (if (namespace kw)
                      (str (namespace kw) "_" (name kw))
                      (name kw))]
            (-> base
                (str/replace "-" "_")
                (str/replace ">" "_")
                (str/replace "/" "_")
                (str/replace "." "_"))))

(defn- kw->lean-type-prefix
       "Converts a formalism kind keyword to a CamelCase prefix."
       [kind-kw]
       (let [raw (kw->lean-name kind-kw)]
            (->> (str/split raw #"_")
                 (mapv str/capitalize)
                 (str/join ""))))

;;; Ref-kind collection

(defn- collect-ref-kinds-for-formalism
       "Scans the registry for all ref-kinds used with a given formalism kind.
  Returns a set of ref-kind keywords."
       [formalism-kind registry]
       (into #{}
             (mapcat
              (fn [[_id morphism]]
                  (cond-> []
                          (= (:from morphism) formalism-kind)
                          (conj (:source-ref-kind morphism))
                          (= (:to morphism) formalism-kind)
                          (conj (:target-ref-kind morphism)))))
             registry))

;;; Per-formalism emission

(defn- emit-ref-kind-inductive
       "Emits an inductive type for a formalism's ref-kinds."
       [prefix ref-kinds]
       (let [sorted (sort (mapv kw->lean-name ref-kinds))
             ctors (str/join "\n"
                             (mapv #(str "  | " %) sorted))]
            (str (doc/lean-doc (str "Ref-kinds for " prefix " formalism."))
                 "inductive " prefix "RefKind where\n"
                 ctors "\n"
                 "  deriving DecidableEq, Repr\n")))

(defn- emit-all-ref-kinds
       "Emits the allRefKinds list and completeness theorem."
       [prefix ref-kinds]
       (let [sorted (sort (mapv kw->lean-name ref-kinds))
             members (str/join ", " (mapv #(str "." %) sorted))]
            (str (doc/lean-doc (str "All ref-kinds for " prefix "."))
                 "def all" prefix "RefKinds : List " prefix "RefKind :=\n"
                 "  [" members "]\n"
                 "\n"
                 (doc/theorem-doc
                  (str "extract-refs handles every ref-kind for " prefix "."))
                 "theorem " (kw->lean-name (keyword prefix))
                 "_ref_exhaustive :\n"
                 "    ∀ k : " prefix "RefKind, k ∈ all"
                 prefix "RefKinds := by\n"
                 "  intro k\n"
                 "  cases k <;> simp [all" prefix "RefKinds]\n")))

(defn- emit-per-formalism
       "Emits ref-extraction exhaustiveness proofs for a single formalism.
  Returns nil if no ref-kinds are used for this formalism."
       [formalism-kind ref-kinds]
       (when (seq ref-kinds)
             (let [prefix (kw->lean-type-prefix formalism-kind)]
                  (str "-- Ref-extraction exhaustiveness for "
                       (name formalism-kind) "\n\n"
                       (emit-ref-kind-inductive prefix ref-kinds)
                       "\n"
                       (emit-all-ref-kinds prefix ref-kinds)))))

;;; Public API

(defn emit-ref-exhaustiveness
      "Emits Lean 4 source proving ref-kind extraction is exhaustive
  per formalism.
  Returns a string of Lean 4 source code."
      [formalisms registry]
      (let [formalism-kinds (keys formalisms)
            per-formalism
            (into []
                  (keep (fn [kind]
                            (let [ref-kinds (collect-ref-kinds-for-formalism
                                             kind registry)]
                                 (emit-per-formalism kind ref-kinds))))
                  (sort-by name formalism-kinds))]
           (str "-- Ref-extraction exhaustiveness verification\n"
                "-- Generated by Pneuma\n\n"
                (str/join "\n\n" per-formalism))))
