(ns pneuma.lean.resolver
    "Lean 4 emission for ResolverGraph formalisms.
  Extends ResolverGraph with ILeanProjectable via extend-protocol.
  Emits inductive ResolverId and Attribute types, resolver declarations
  as input/output attribute sets, and reachability theorem scaffolding."
    (:require [clojure.string :as str]
              [pneuma.lean.doc :as doc]
              [pneuma.lean.protocol :as lp])
    (:import [pneuma.formalism.resolver ResolverGraph]))

(defn- kw->lean-name
       [kw]
       (let [base (if (namespace kw)
                      (str (namespace kw) "_" (name kw))
                      (name kw))]
            (-> base
                (str/replace "-" "_")
                (str/replace "/" "_")
                (str/replace "." "_"))))

(defn- emit-inductive
       "Emits a Lean inductive type from a set of keywords."
       [type-name keywords]
       (let [sorted (sort (mapv kw->lean-name keywords))
             ctors (str/join "\n"
                             (mapv #(str "  | " %) sorted))]
            (str "inductive " type-name " where\n"
                 ctors "\n"
                 "  deriving DecidableEq, Repr\n")))

(defn- emit-attr-set-def
       "Emits a Lean list definition for a set of attributes."
       [def-name attrs]
       (let [sorted (sort (mapv kw->lean-name attrs))
             members (str/join ", " (mapv #(str "." %) sorted))]
            (str "def " def-name " : List Attribute :=\n"
                 "  [" members "]\n")))

(defn- emit-resolver-defs
       "Emits input/output attribute set definitions for each resolver."
       [declarations]
       (str/join "\n"
                 (mapv (fn [[_ decl]]
                           (let [rname (kw->lean-name (:id decl))]
                                (str (emit-attr-set-def
                                      (str rname "_input")
                                      (:input decl))
                                     "\n"
                                     (emit-attr-set-def
                                      (str rname "_output")
                                      (:output decl)))))
                       (sort-by (comp name :id val) declarations))))

(defn- emit-completeness
       "Emits allResolvers list and completeness theorem."
       [id resolver-ids]
       (let [sorted (sort (mapv kw->lean-name resolver-ids))
             members (str/join ", " (mapv #(str "." %) sorted))
             n (count resolver-ids)]
            (str (doc/lean-doc (str "Exhaustive list of all resolvers in ResolverGraph"
                                    (when id (str " " (doc/id-str id))) "."))
                 "def allResolvers : List ResolverId :=\n"
                 "  [" members "]\n"
                 "\n"
                 (doc/theorem-doc "Every member of ResolverId appears in allResolvers. Proved by case analysis.")
                 "theorem allResolvers_complete :\n"
                 "    ∀ r : ResolverId, r ∈ allResolvers := by\n"
                 "  intro r\n"
                 "  cases r <;> simp [allResolvers]\n"
                 "\n"
                 (doc/theorem-doc (str "allResolvers contains exactly " n " members."))
                 "theorem allResolvers_count :\n"
                 "    allResolvers.length = " n " := by\n"
                 "  rfl\n")))

(defn- emit-reachability-scaffold
       "Emits reachability definition and theorem target."
       []
       (str "\n-- Reachability: chase fixpoint over resolver hyperedges\n"
            (doc/lean-doc "A set of attributes is closed if, for every resolver whose"
                          "inputs are in the set, its outputs are also in the set.")
            "def closed (s : List Attribute) : Prop :=\n"
            "  sorry\n"
            "\n-- PROOF TARGET: the chase terminates and computes the closure\n"
            (doc/theorem-doc "The chase algorithm terminates and computes the closure of the initial attribute set.")
            "theorem chase_terminates :\n"
            "    ∀ (init : List Attribute), ∃ (s : List Attribute),\n"
            "      init ⊆ s ∧ closed s := by\n"
            "  sorry\n"))

(defn- emit-resolver-lean
       [id declarations]
       (let [resolver-ids (keys declarations)
             id-label (if id (str " " (doc/id-str id)) "")
             all-attrs (into #{}
                             (mapcat (fn [[_ decl]]
                                         (concat (:input decl) (:output decl))))
                             declarations)]
            (str "-- Generated by Pneuma from ResolverGraph" id-label "\n\n"
                 (doc/type-doc "ResolverGraph" id
                               (str "Resolver identifiers in ResolverGraph" id-label "."))
                 (emit-inductive "ResolverId" resolver-ids)
                 "\n"
                 (doc/type-doc "ResolverGraph" id
                               (str "Attributes reachable by resolvers in ResolverGraph" id-label "."))
                 (emit-inductive "Attribute" all-attrs)
                 "\n"
                 (emit-resolver-defs declarations)
                 "\n"
                 (emit-completeness id resolver-ids)
                 (emit-reachability-scaffold))))

(extend-protocol lp/ILeanProjectable
                 ResolverGraph
                 (->lean [this]
                         (emit-resolver-lean (:id this) (:declarations this))))
