(ns pneuma.lean.statechart
    "Lean 4 emission for Statechart formalisms.
  Extends Statechart with ILeanProjectable via extend-protocol.
  Emits inductive State type, step function, reachability definition,
  and chart safety theorem targets."
    (:require [clojure.string :as str]
              [pneuma.lean.doc :as doc]
              [pneuma.lean.protocol :as lp])
    (:import [pneuma.formalism.statechart Statechart]))

(defn- kw->lean-name
       [kw]
       (-> (name kw)
           (str/replace "-" "_")
           (str/replace "/" "_")))

(defn- emit-state-inductive
       [states]
       (let [sorted (sort-by name states)
             ctors (str/join "\n"
                             (mapv #(str "  | " (kw->lean-name %)) sorted))]
            (str "inductive State where\n"
                 ctors "\n"
                 "  deriving DecidableEq, Repr\n")))

(defn- emit-event-inductive
       [transitions]
       (let [events (sort (into #{} (map (comp kw->lean-name :event)) transitions))
             ctors (str/join "\n"
                             (mapv #(str "  | " %) events))]
            (str "inductive Event where\n"
                 ctors "\n"
                 "  deriving DecidableEq, Repr\n")))

(defn- emit-step-function
       "Emits the step function δ : State → Event → State."
       [transitions]
       (let [clauses (str/join "\n"
                               (mapv (fn [{:keys [source event target]}]
                                         (str "  | ." (kw->lean-name source)
                                              ", ." (kw->lean-name event)
                                              " => ." (kw->lean-name target)))
                                     transitions))]
            (str "def step (s : State) (e : Event) : State :=\n"
                 "  match s, e with\n"
                 clauses "\n"
                 "  | s, _ => s\n")))

(defn- emit-reachability
       [initial-state]
       (str (doc/lean-doc "The starting state of the statechart.")
            "def initialState : State := ." (kw->lean-name initial-state) "\n"
            "\n"
            (doc/lean-doc "A state is reachable if some event sequence from initialState leads to it.")
            "def reachable (s : State) : Prop :=\n"
            "  ∃ (events : List Event), events.foldl step initialState = s\n"))

(defn- emit-safety-theorem
       [id]
       (str "\n-- chart_safety_aux: induction over event list with accumulator\n"
            (doc/theorem-doc "Helper lemma: an invariant preserved by step is preserved by any event sequence.")
            "theorem chart_safety_aux (inv : State → Prop)\n"
            "    (h_step : ∀ s e, inv s → inv (step s e))\n"
            "    (s₀ : State) (h₀ : inv s₀)\n"
            "    (events : List Event) :\n"
            "    inv (events.foldl step s₀) := by\n"
            "  induction events generalizing s₀ with\n"
            "  | nil => exact h₀\n"
            "  | cons e es ih => exact ih (step s₀ e) (h_step s₀ e h₀)\n"
            "\n-- PROOF TARGET: chart safety — all reachable states satisfy an invariant\n"
            "-- Instantiate `inv` with your specific safety property.\n"
            (doc/theorem-doc
             (str "For any invariant preserved by one step of the statechart"
                  (when id (str " " (doc/id-str id)))
                  ", all reachable states satisfy it."))
            "theorem chart_safety (inv : State → Prop)\n"
            "    (h_init : inv initialState)\n"
            "    (h_step : ∀ s e, inv s → inv (step s e)) :\n"
            "    ∀ s, reachable s → inv s := by\n"
            "  intro s ⟨events, hc⟩\n"
            "  -- The state s was reached by folding `step` over `events`\n"
            "  subst hc\n"
            "  -- Apply the induction lemma to the event sequence\n"
            "  exact chart_safety_aux inv h_step initialState h_init events\n"))

(defn- emit-determinism-theorem
       [_id]
       (str "\n-- PROOF TARGET: step is deterministic (follows from being a pure function)\n"
            (doc/theorem-doc "The step function is deterministic: equal inputs always produce equal outputs.")
            "theorem step_deterministic :\n"
            "    ∀ s e, step s e = step s e := by\n"
            "  intros; rfl\n"))

(defn- flat-initial-state
       "Gets the initial leaf state for non-parallel charts.
  For parallel charts, picks the first initial value."
       [initial]
       (first (vals initial)))

(defn- emit-statechart-lean
       [{:keys [id states transitions initial]}]
       (let [init-state (flat-initial-state initial)
             id-label (if id (str " " (doc/id-str id)) "")]
            (str "-- Generated by Pneuma from Statechart" id-label "\n\n"
                 (doc/type-doc "Statechart" id
                               (str "States of the" id-label " statechart."))
                 (emit-state-inductive states)
                 "\n"
                 (doc/type-doc "Statechart" id
                               (str "Events that drive transitions in the" id-label " statechart."))
                 (emit-event-inductive transitions)
                 "\n"
                 (doc/lean-doc (str "Transition function δ for Statechart" id-label ".")
                               "Given a state and event, returns the successor state.")
                 (emit-step-function transitions)
                 "\n"
                 (emit-reachability init-state)
                 (emit-safety-theorem id)
                 (emit-determinism-theorem id))))

(extend-protocol lp/ILeanProjectable
                 Statechart
                 (->lean [this]
                         (emit-statechart-lean
                          {:id (:id this)
                           :states (:states this)
                           :transitions (:transitions this)
                           :initial (:initial this)})))
