(ns pneuma.lean.structural
    "Lean 4 emission for StructuralMorphism boundaries.
  Extends StructuralMorphism with ILeanConnection via extend-protocol.
  Emits inductive types for source outputs, an opaque schema validation
  predicate, and the structural boundary proposition."
    (:require [clojure.string :as str]
              [pneuma.lean.protocol :as lp]
              [pneuma.protocol :as p])
    (:import [pneuma.morphism.structural StructuralMorphism]))

(defn- kw->lean-name
       "Converts a keyword to a valid Lean identifier."
       [kw]
       (let [base (if (namespace kw)
                      (str (namespace kw) "_" (name kw))
                      (name kw))]
            (-> base
                (str/replace "-" "_")
                (str/replace ">" "_")
                (str/replace "/" "_")
                (str/replace "." "_"))))

(defn- morphism-id->lean-prefix
       "Converts a morphism id keyword to a CamelCase Lean prefix."
       [id-kw]
       (let [raw (kw->lean-name id-kw)]
            (->> (str/split raw #"_")
                 (mapv str/capitalize)
                 (str/join ""))))

(defn- emit-inductive
       "Emits a Lean inductive type from a set of keywords."
       [type-name refs]
       (let [sorted (sort (mapv kw->lean-name refs))
             ctors (str/join "\n"
                             (mapv #(str "  | " %) sorted))]
            (str "inductive " type-name " where\n"
                 ctors "\n"
                 "  deriving DecidableEq, Repr\n")))

(defn- emit-all-list
       "Emits an allXxx list and completeness theorem."
       [type-name refs]
       (let [sorted (sort (mapv kw->lean-name refs))
             members (str/join ", " (mapv #(str "." %) sorted))]
            (str "def all" type-name " : List " type-name " :=\n"
                 "  [" members "]\n"
                 "\ntheorem all" type-name "_complete :\n"
                 "    ∀ x : " type-name ", x ∈ all" type-name " := by\n"
                 "  intro x\n"
                 "  cases x <;> simp [all" type-name "]\n")))

(defn- emit-validate-fn
       "Emits an opaque validation predicate for schema conformance.
  Schema validation is opaque in Lean since it originates from Malli."
       [prefix]
       (str "-- Schema validation is opaque: originates from Malli at the Clojure level.\n"
            "-- The predicate stands for: m/validate target-schema output\n"
            "opaque " prefix "Valid : " prefix "Output → Prop := fun _ => True\n"))

(defn- emit-boundary-proposition
       "Emits the structural boundary proposition: every source output
  conforms to the target schema."
       [prefix]
       (str "-- PROOF TARGET: every source output validates against the target schema\n"
            "theorem " prefix "_structural_boundary :\n"
            "    ∀ o : " prefix "Output, " prefix "Valid o := by\n"
            "  sorry\n"))

(defn- emit-structural-lean
       "Generates Lean 4 source for a StructuralMorphism boundary."
       [{:keys [id from to source-ref-kind target-ref-kind]}
        source-outputs]
       (let [prefix (morphism-id->lean-prefix id)]
            (str "-- Generated by Pneuma from StructuralMorphism " id "\n"
                 "-- Boundary: " (name from) " → " (name to) "\n"
                 "-- Source ref-kind: " (name source-ref-kind)
                 ", Target ref-kind: " (name target-ref-kind) "\n\n"
                 (emit-inductive (str prefix "Output") source-outputs)
                 "\n"
                 (emit-all-list (str prefix "Output") source-outputs)
                 "\n"
                 (emit-validate-fn prefix)
                 "\n"
                 (emit-boundary-proposition prefix))))

(extend-protocol lp/ILeanConnection
                 StructuralMorphism
                 (->lean-conn [this source _target]
                              (let [source-outputs (p/extract-refs source
                                                                   (:source-ref-kind this))]
                                   (emit-structural-lean
                                    this source-outputs))))
