(ns pneuma.lean.system
    "Emits a unified Lean 4 file for a complete Pneuma specification.
  Runs the gap report internally and emits proved theorems for
  conforming morphisms, sorry placeholders for failing ones. The Lean
  output is a direct projection of Pneuma's own conformance check."
    (:require [clojure.string :as str]
              [pneuma.gap.core :as gap]))

;;; Helpers

(defn- kw->lean-name
       "Converts a Clojure keyword to a valid Lean identifier."
       [kw]
       (-> (name kw)
           (str/replace #"^->" "")
           (str/replace "-" "_")
           (str/replace "/" "_")))

(defn- kw->lean-type
       "Converts a type keyword to a Lean type name."
       [kw]
       (let [n (name kw)]
            (if (Character/isUpperCase ^char (first n))
                n
                (str/capitalize n))))

;;; Emission sections

(defn- emit-header
       [spec-name conforms?]
       (str "-- Generated by Pneuma system-level ->lean projection\n"
            "-- Source: " spec-name "\n"
            "-- Gap report: " (if conforms? "ALL CONFORMING" "HAS FAILURES") "\n"
            "-- Proofs are mechanically generated from Pneuma's conformance check.\n"
            "-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.\n\n"))

(def ^:private lean-builtins
     "Lean 4 built-in type names that must not be redeclared."
     #{"Bool" "Nat" "Int" "String" "Unit" "Prop" "Type" "List" "Option" "Char" "Float" "UInt8" "UInt16" "UInt32" "UInt64"})

(defn- emit-opaque-types
       "Emits opaque type declarations for all referenced types,
  skipping Lean builtins."
       [operations]
       (let [type-kws (into (sorted-set)
                            (mapcat (fn [[_ {:keys [input output]}]]
                                        (conj (vec (vals input)) output)))
                            operations)
             non-builtin (remove #(lean-builtins (kw->lean-type %)) type-kws)]
            (str (str/join "\n"
                           (mapv #(str "opaque " (kw->lean-type %) " : Type := Unit")
                                 non-builtin))
                 "\n")))

(defn- emit-op-type
       "Emits the inductive Op type from an EffectSignature."
       [operations]
       (let [sorted-ops (sort (map (comp kw->lean-name key) operations))]
            (str "\ninductive Op where\n"
                 (str/join "\n" (mapv #(str "  | " %) sorted-ops))
                 "\n  deriving DecidableEq, Repr\n")))

(defn- emit-all-ops
       "Emits the exhaustive list of all operations and completeness proof."
       [operations]
       (let [sorted-ops (sort (map (comp kw->lean-name key) operations))
             members (str/join ", " (mapv #(str "." %) sorted-ops))
             n (count operations)]
            (str "\ndef allOps : List Op :=\n"
                 "  [" members "]\n"
                 "\ntheorem allOps_complete :\n"
                 "    ∀ op : Op, op ∈ allOps := by\n"
                 "  intro op\n"
                 "  cases op <;> simp [allOps]\n"
                 "\ntheorem allOps_count :\n"
                 "    allOps.length = " n " := by\n"
                 "  rfl\n")))

(defn- emit-cap-dispatch
       "Emits a capability set's dispatch operations as a List Op."
       [caps-id dispatch-refs]
       (let [id-str (kw->lean-name caps-id)
             sorted-ops (sort (mapv kw->lean-name dispatch-refs))
             members (str/join ", " (mapv #(str "." %) sorted-ops))]
            (str "\ndef " id-str "_dispatch : List Op :=\n"
                 "  [" members "]\n")))

(defn- morphism-status
       "Looks up the status of a morphism in the gap report."
       [report morphism-id]
       (let [morph-gaps (:morphism-gaps report)]
            (some (fn [g]
                      (when (= morphism-id (:id g))
                            (:status g)))
                  morph-gaps)))

(defn- emit-containment-proof
       "Emits a containment theorem. Uses `decide` if the morphism conforms
  in the gap report, `sorry` with a diagnostic comment if it fails."
       [caps-id morph-id status dangling-refs]
       (let [id-str (kw->lean-name caps-id)]
            (str "\n-- Morphism " (name morph-id) ": " id-str " dispatch ⊆ allOps"
                 " [" (name status) "]\n"
                 "theorem " id-str "_dispatch_valid :\n"
                 "    ∀ op : Op, op ∈ " id-str "_dispatch"
                 " → op ∈ allOps := by\n"
                 (if (= :conforms status)
                     "  decide\n"
                     (str "  sorry -- FAILING: dangling refs "
                          (pr-str dangling-refs) "\n")))))

(defn- emit-system-theorem
       "Emits the top-level system theorem. Proved if all morphisms conform."
       [cap-ids all-conform?]
       (let [conjuncts (str/join " ∧\n    "
                                 (mapv (fn [id]
                                           (let [id-str (kw->lean-name id)]
                                                (str "(∀ op, op ∈ " id-str
                                                     "_dispatch → op ∈ allOps)")))
                                       (sort-by name cap-ids)))]
            (str "\n-- System-level: all capability dispatch sets reference valid operations\n"
                 "theorem system_conformance :\n"
                 "    " conjuncts " := by\n"
                 (if all-conform?
                     (str "  exact ⟨"
                          (str/join ", "
                                    (mapv (fn [id]
                                              (str (kw->lean-name id) "_dispatch_valid"))
                                          (sort-by name cap-ids)))
                          "⟩\n")
                     "  sorry -- some morphisms have failures\n"))))

;;; Public API

(defn emit-system-lean
      "Emits a unified Lean 4 file for a complete specification.
  Runs the gap report and uses the results to generate proofs:
  conforming morphisms get `decide` proofs, failing morphisms get
  `sorry` with diagnostic comments.
  Takes a spec name string and the same config map as gap-report:
  {:formalisms {...} :registry {...}}.
  Returns a string of Lean 4 source code."
      [spec-name config]
      (let [report (gap/gap-report config)
            conforms? (not (gap/has-failures? report))
            formalisms (:formalisms config)
            effect-sig (some (fn [[_ v]]
                                 (when (instance?
                                        pneuma.formalism.effect_signature.EffectSignature v)
                                       v))
                             formalisms)
            cap-sets (into {}
                           (keep (fn [[k v]]
                                     (when (instance?
                                            pneuma.formalism.capability.CapabilitySet v)
                                           [k v])))
                           formalisms)
            operations (:operations effect-sig)
            ;; Build morphism-id → caps-id mapping from registry
            registry (:registry config)
            cap-morphisms (into {}
                                (keep (fn [[morph-id morph]]
                                          (let [from-key (:from morph)
                                                caps-entry (get cap-sets from-key)]
                                               (when caps-entry
                                                     [morph-id {:caps-id (:id caps-entry)
                                                                :from-key from-key}]))))
                                registry)]
           (str (emit-header spec-name conforms?)
                (emit-opaque-types operations)
                (emit-op-type operations)
                (emit-all-ops operations)
                (str/join ""
                          (mapv (fn [[_ caps]]
                                    (emit-cap-dispatch (:id caps) (:dispatch caps)))
                                (sort-by (comp name key) cap-sets)))
                (str/join ""
                          (mapv (fn [[morph-id {:keys [caps-id]}]]
                                    (let [status (morphism-status report morph-id)
                                          gap-detail (some (fn [g]
                                                               (when (= morph-id (:id g))
                                                                     (:detail g)))
                                                           (:morphism-gaps report))
                                          dangling (:dangling-refs gap-detail)]
                                         (emit-containment-proof
                                          caps-id morph-id
                                          (or status :conforms)
                                          dangling)))
                                (sort-by (comp name key) cap-morphisms)))
                (emit-system-theorem
                 (mapv (comp :id val) cap-sets)
                 conforms?))))
