(ns pneuma.lean.type-schema
    "Lean 4 emission for TypeSchema formalisms.
  Extends TypeSchema with ILeanProjectable via extend-protocol."
    (:require [clojure.string :as str]
              [pneuma.lean.doc :as doc]
              [pneuma.lean.protocol :as lp])
    (:import [pneuma.formalism.type_schema TypeSchema]))

(defn- kw->lean-name
       [kw]
       (-> (name kw)
           (str/replace "-" "_")
           (str/replace "/" "_")))

(defn- emit-type-schema-lean
       [id types-map]
       (let [sorted-kws (sort-by name (keys types-map))
             id-label (if id (str " " (doc/id-str id)) "")
             ctors (str/join "\n"
                             (mapv #(str "  | " (kw->lean-name %)) sorted-kws))
             members (str/join ", "
                               (mapv #(str "." (kw->lean-name %)) sorted-kws))
             n (count types-map)]
            (str "-- Generated by Pneuma from TypeSchema" id-label "\n\n"
                 (doc/type-doc "TypeSchema" id
                               (str "Type identifiers declared in TypeSchema" id-label "."))
                 "inductive TypeId where\n"
                 ctors "\n"
                 "  deriving DecidableEq, Repr\n"
                 "\n"
                 (doc/lean-doc (str "Exhaustive list of all types in TypeSchema" id-label "."))
                 "def allTypeIds : List TypeId :=\n"
                 "  [" members "]\n"
                 "\n"
                 (doc/theorem-doc "Every member of TypeId appears in allTypeIds. Proved by case analysis.")
                 "theorem allTypeIds_complete :\n"
                 "    ∀ t : TypeId, t ∈ allTypeIds := by\n"
                 "  intro t\n"
                 "  cases t <;> simp [allTypeIds]\n"
                 "\n"
                 (doc/theorem-doc (str "allTypeIds contains exactly " n " members."))
                 "theorem allTypeIds_count :\n"
                 "    allTypeIds.length = " n " := by\n"
                 "  rfl\n")))

(extend-protocol lp/ILeanProjectable
                 TypeSchema
                 (->lean [this]
                         (emit-type-schema-lean (:id this) (:types this))))
