(ns pneuma.lean.type-schema
    "Lean 4 emission for TypeSchema formalisms.
  Extends TypeSchema with ILeanProjectable via extend-protocol."
    (:require [clojure.string :as str]
              [pneuma.lean.protocol :as lp])
    (:import [pneuma.formalism.type_schema TypeSchema]))

(defn- kw->lean-name
       [kw]
       (-> (name kw)
           (str/replace "-" "_")
           (str/replace "/" "_")))

(defn- emit-type-schema-lean
       [types-map]
       (let [sorted-kws (sort-by name (keys types-map))
             ctors (str/join "\n"
                             (mapv #(str "  | " (kw->lean-name %)) sorted-kws))
             members (str/join ", "
                               (mapv #(str "." (kw->lean-name %)) sorted-kws))
             n (count types-map)]
            (str "-- Generated by Pneuma from TypeSchema\n\n"
                 "inductive TypeId where\n"
                 ctors "\n"
                 "  deriving DecidableEq, Repr\n"
                 "\ndef allTypeIds : List TypeId :=\n"
                 "  [" members "]\n"
                 "\ntheorem allTypeIds_complete :\n"
                 "    ∀ t : TypeId, t ∈ allTypeIds := by\n"
                 "  intro t\n"
                 "  cases t <;> simp [allTypeIds]\n"
                 "\ntheorem allTypeIds_count :\n"
                 "    allTypeIds.length = " n " := by\n"
                 "  rfl\n")))

(extend-protocol lp/ILeanProjectable
                 TypeSchema
                 (->lean [this]
                         (emit-type-schema-lean (:types this))))
