namespace CapabilityRefExhaustive

-- Ref-extraction exhaustiveness verification
-- Generated by Pneuma

-- Ref-extraction exhaustiveness for api

/-- Ref-kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureApi. -/
def allEffectSignatureApiRefKinds : List EffectSignatureApiRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureApi. -/
theorem EffectSignatureApi_ref_exhaustive :
    ∀ k : EffectSignatureApiRefKind, k ∈ allEffectSignatureApiRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiRefKinds]


-- Ref-extraction exhaustiveness for cap-api

/-- Ref-kinds for CapabilitySetCapApi formalism. -/
inductive CapabilitySetCapApiRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetCapApi. -/
def allCapabilitySetCapApiRefKinds : List CapabilitySetCapApiRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetCapApi. -/
theorem CapabilitySetCapApi_ref_exhaustive :
    ∀ k : CapabilitySetCapApiRefKind, k ∈ allCapabilitySetCapApiRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetCapApiRefKinds]


-- Ref-extraction exhaustiveness for cap-ref-kinds

/-- Ref-kinds for CapabilitySetCapRefKinds formalism. -/
inductive CapabilitySetCapRefKindsRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetCapRefKinds. -/
def allCapabilitySetCapRefKindsRefKinds : List CapabilitySetCapRefKindsRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetCapRefKinds. -/
theorem CapabilitySetCapRefKinds_ref_exhaustive :
    ∀ k : CapabilitySetCapRefKindsRefKind, k ∈ allCapabilitySetCapRefKindsRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetCapRefKindsRefKinds]


-- Ref-extraction exhaustiveness for refs

/-- Ref-kinds for EffectSignatureRefs formalism. -/
inductive EffectSignatureRefsRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureRefs. -/
def allEffectSignatureRefsRefKinds : List EffectSignatureRefsRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureRefs. -/
theorem EffectSignatureRefs_ref_exhaustive :
    ∀ k : EffectSignatureRefsRefKind, k ∈ allEffectSignatureRefsRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureRefsRefKinds]


-- Ref-extraction exhaustiveness for type-schema

/-- Ref-kinds for TypeSchema formalism. -/
inductive TypeSchemaRefKind where
  | type_ids
  deriving DecidableEq, Repr

/-- All ref-kinds for TypeSchema. -/
def allTypeSchemaRefKinds : List TypeSchemaRefKind :=
  [.type_ids]

/-- extract-refs handles every ref-kind for TypeSchema. -/
theorem TypeSchema_ref_exhaustive :
    ∀ k : TypeSchemaRefKind, k ∈ allTypeSchemaRefKinds := by
  intro k
  cases k <;> simp [allTypeSchemaRefKinds]

end CapabilityRefExhaustive
