-- Generated by Pneuma system-level ->lean projection
-- Source: Capability
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque CapabilitySet : Type := Unit
opaque Keyword : Type := Unit
opaque KeywordSet : Type := Unit

inductive Op where
  | all_refs
  | capability_set
  | dispatch_refs
  | query_refs
  | subscribe_refs
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.all_refs, .capability_set, .dispatch_refs, .query_refs, .subscribe_refs]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 5 := by
  rfl

def cap_api_dispatch : List Op :=
  [.capability_set]

def cap_ref_kinds_dispatch : List Op :=
  [.all_refs, .dispatch_refs, .query_refs, .subscribe_refs]

-- Morphism api-caps->api-ops: cap_api dispatch ⊆ allOps [conforms]
theorem cap_api_dispatch_valid :
    ∀ op : Op, op ∈ cap_api_dispatch → op ∈ allOps := by
  decide

-- Morphism ref-kind-caps->ref-ops: cap_ref_kinds dispatch ⊆ allOps [conforms]
theorem cap_ref_kinds_dispatch_valid :
    ∀ op : Op, op ∈ cap_ref_kinds_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ cap_api_dispatch → op ∈ allOps) ∧
    (∀ op, op ∈ cap_ref_kinds_dispatch → op ∈ allOps) := by
  exact ⟨cap_api_dispatch_valid, cap_ref_kinds_dispatch_valid⟩
