namespace CapabilityMonitorSchema

-- Monitor-schema consistency verification
-- Generated by Pneuma

-- Monitor-schema consistency for api

/-- Gap kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureApi. -/
def allEffectSignatureApiGapKinds : List EffectSignatureApiGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_gap_kinds_complete :
    ∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiGapKinds]

/-- Gap statuses for EffectSignatureApi formalism. -/
inductive EffectSignatureApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureApi. -/
def allEffectSignatureApiStatuses : List EffectSignatureApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_statuses_complete :
    ∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureApiStatuses]

/-- Monitor-schema consistency for EffectSignatureApi: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureApi_monitor_schema_consistent :
    (∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds) ∧
    (∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses) := by
  exact ⟨EffectSignatureApi_gap_kinds_complete, EffectSignatureApi_statuses_complete⟩


-- Monitor-schema consistency for cap-api

/-- Gap kinds for CapabilitySetCapApi formalism. -/
inductive CapabilitySetCapApiGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetCapApi. -/
def allCapabilitySetCapApiGapKinds : List CapabilitySetCapApiGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetCapApi is accounted for. -/
theorem CapabilitySetCapApi_gap_kinds_complete :
    ∀ k : CapabilitySetCapApiGapKind, k ∈ allCapabilitySetCapApiGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetCapApiGapKinds]

/-- Gap statuses for CapabilitySetCapApi formalism. -/
inductive CapabilitySetCapApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetCapApi. -/
def allCapabilitySetCapApiStatuses : List CapabilitySetCapApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetCapApi is accounted for. -/
theorem CapabilitySetCapApi_statuses_complete :
    ∀ s : CapabilitySetCapApiStatus, s ∈ allCapabilitySetCapApiStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetCapApiStatuses]

/-- Monitor-schema consistency for CapabilitySetCapApi: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetCapApi_monitor_schema_consistent :
    (∀ k : CapabilitySetCapApiGapKind, k ∈ allCapabilitySetCapApiGapKinds) ∧
    (∀ s : CapabilitySetCapApiStatus, s ∈ allCapabilitySetCapApiStatuses) := by
  exact ⟨CapabilitySetCapApi_gap_kinds_complete, CapabilitySetCapApi_statuses_complete⟩


-- Monitor-schema consistency for cap-ref-kinds

/-- Gap kinds for CapabilitySetCapRefKinds formalism. -/
inductive CapabilitySetCapRefKindsGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetCapRefKinds. -/
def allCapabilitySetCapRefKindsGapKinds : List CapabilitySetCapRefKindsGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetCapRefKinds is accounted for. -/
theorem CapabilitySetCapRefKinds_gap_kinds_complete :
    ∀ k : CapabilitySetCapRefKindsGapKind, k ∈ allCapabilitySetCapRefKindsGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetCapRefKindsGapKinds]

/-- Gap statuses for CapabilitySetCapRefKinds formalism. -/
inductive CapabilitySetCapRefKindsStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetCapRefKinds. -/
def allCapabilitySetCapRefKindsStatuses : List CapabilitySetCapRefKindsStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetCapRefKinds is accounted for. -/
theorem CapabilitySetCapRefKinds_statuses_complete :
    ∀ s : CapabilitySetCapRefKindsStatus, s ∈ allCapabilitySetCapRefKindsStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetCapRefKindsStatuses]

/-- Monitor-schema consistency for CapabilitySetCapRefKinds: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetCapRefKinds_monitor_schema_consistent :
    (∀ k : CapabilitySetCapRefKindsGapKind, k ∈ allCapabilitySetCapRefKindsGapKinds) ∧
    (∀ s : CapabilitySetCapRefKindsStatus, s ∈ allCapabilitySetCapRefKindsStatuses) := by
  exact ⟨CapabilitySetCapRefKinds_gap_kinds_complete, CapabilitySetCapRefKinds_statuses_complete⟩


-- Monitor-schema consistency for refs

/-- Gap kinds for EffectSignatureRefs formalism. -/
inductive EffectSignatureRefsGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureRefs. -/
def allEffectSignatureRefsGapKinds : List EffectSignatureRefsGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureRefs is accounted for. -/
theorem EffectSignatureRefs_gap_kinds_complete :
    ∀ k : EffectSignatureRefsGapKind, k ∈ allEffectSignatureRefsGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureRefsGapKinds]

/-- Gap statuses for EffectSignatureRefs formalism. -/
inductive EffectSignatureRefsStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureRefs. -/
def allEffectSignatureRefsStatuses : List EffectSignatureRefsStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureRefs is accounted for. -/
theorem EffectSignatureRefs_statuses_complete :
    ∀ s : EffectSignatureRefsStatus, s ∈ allEffectSignatureRefsStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureRefsStatuses]

/-- Monitor-schema consistency for EffectSignatureRefs: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureRefs_monitor_schema_consistent :
    (∀ k : EffectSignatureRefsGapKind, k ∈ allEffectSignatureRefsGapKinds) ∧
    (∀ s : EffectSignatureRefsStatus, s ∈ allEffectSignatureRefsStatuses) := by
  exact ⟨EffectSignatureRefs_gap_kinds_complete, EffectSignatureRefs_statuses_complete⟩


-- Monitor-schema consistency for type-schema

/-- Gap kinds for TypeSchema formalism. -/
inductive TypeSchemaGapKind where
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for TypeSchema. -/
def allTypeSchemaGapKinds : List TypeSchemaGapKind :=
  [.unknown_type]

/-- Every gap kind for TypeSchema is accounted for. -/
theorem TypeSchema_gap_kinds_complete :
    ∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds := by
  intro k
  cases k <;> simp [allTypeSchemaGapKinds]

/-- Gap statuses for TypeSchema formalism. -/
inductive TypeSchemaStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for TypeSchema. -/
def allTypeSchemaStatuses : List TypeSchemaStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for TypeSchema is accounted for. -/
theorem TypeSchema_statuses_complete :
    ∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses := by
  intro s
  cases s <;> simp [allTypeSchemaStatuses]

/-- Monitor-schema consistency for TypeSchema: both gap-kind and status enumerations are exhaustive. -/
theorem TypeSchema_monitor_schema_consistent :
    (∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds) ∧
    (∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses) := by
  exact ⟨TypeSchema_gap_kinds_complete, TypeSchema_statuses_complete⟩

end CapabilityMonitorSchema
