-- Generated by Pneuma ->lean projection
-- Source: pneuma.protocol-spec capability sets

-- Generated by Pneuma from CapabilitySet :formalism-record

inductive Formalism_recordOp where
  | gap_type
  | gen
  | monitor
  | schema
  | extract_refs
  deriving DecidableEq, Repr

def formalism_record_dispatch : List Formalism_recordOp :=
  [.gap_type, .gen, .monitor, .schema, .extract_refs]

-- PROOF TARGET: dispatch ops are within the declared set
theorem formalism_record_dispatch_bounded :
    ∀ op : Formalism_recordOp, op ∈ formalism_record_dispatch → op ∈ formalism_record_dispatch := by
  intro op h
  exact h

-- Generated by Pneuma from CapabilitySet :morphism-record

inductive Morphism_recordOp where
  | check
  deriving DecidableEq, Repr

def morphism_record_dispatch : List Morphism_recordOp :=
  [.check]

-- PROOF TARGET: dispatch ops are within the declared set
theorem morphism_record_dispatch_bounded :
    ∀ op : Morphism_recordOp, op ∈ morphism_record_dispatch → op ∈ morphism_record_dispatch := by
  intro op h
  exact h
