-- Generated by Pneuma system-level ->lean projection
-- Source: Containment
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque ContainmentMorphism : Type := Unit
opaque GapSeq : Type := Unit
opaque IReferenceable : Type := Unit
opaque Keyword : Type := Unit
opaque RefinementMap : Type := Unit

inductive Op where
  | check
  | containment_morphism
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.check, .containment_morphism]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 2 := by
  rfl

def ct_api_dispatch : List Op :=
  [.containment_morphism]

def ct_check_dispatch : List Op :=
  [.check]

-- Morphism api-caps->api-ops: ct_api dispatch ⊆ allOps [conforms]
theorem ct_api_dispatch_valid :
    ∀ op : Op, op ∈ ct_api_dispatch → op ∈ allOps := by
  decide

-- Morphism check-caps->check-ops: ct_check dispatch ⊆ allOps [conforms]
theorem ct_check_dispatch_valid :
    ∀ op : Op, op ∈ ct_check_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ ct_api_dispatch → op ∈ allOps) ∧
    (∀ op, op ∈ ct_check_dispatch → op ∈ allOps) := by
  exact ⟨ct_api_dispatch_valid, ct_check_dispatch_valid⟩
