namespace ContainmentMonitorSchema

-- Monitor-schema consistency verification
-- Generated by Pneuma

-- Monitor-schema consistency for api

/-- Gap kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureApi. -/
def allEffectSignatureApiGapKinds : List EffectSignatureApiGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_gap_kinds_complete :
    ∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiGapKinds]

/-- Gap statuses for EffectSignatureApi formalism. -/
inductive EffectSignatureApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureApi. -/
def allEffectSignatureApiStatuses : List EffectSignatureApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_statuses_complete :
    ∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureApiStatuses]

/-- Monitor-schema consistency for EffectSignatureApi: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureApi_monitor_schema_consistent :
    (∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds) ∧
    (∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses) := by
  exact ⟨EffectSignatureApi_gap_kinds_complete, EffectSignatureApi_statuses_complete⟩


-- Monitor-schema consistency for check

/-- Gap kinds for EffectSignatureCheck formalism. -/
inductive EffectSignatureCheckGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureCheck. -/
def allEffectSignatureCheckGapKinds : List EffectSignatureCheckGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureCheck is accounted for. -/
theorem EffectSignatureCheck_gap_kinds_complete :
    ∀ k : EffectSignatureCheckGapKind, k ∈ allEffectSignatureCheckGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureCheckGapKinds]

/-- Gap statuses for EffectSignatureCheck formalism. -/
inductive EffectSignatureCheckStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureCheck. -/
def allEffectSignatureCheckStatuses : List EffectSignatureCheckStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureCheck is accounted for. -/
theorem EffectSignatureCheck_statuses_complete :
    ∀ s : EffectSignatureCheckStatus, s ∈ allEffectSignatureCheckStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureCheckStatuses]

/-- Monitor-schema consistency for EffectSignatureCheck: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureCheck_monitor_schema_consistent :
    (∀ k : EffectSignatureCheckGapKind, k ∈ allEffectSignatureCheckGapKinds) ∧
    (∀ s : EffectSignatureCheckStatus, s ∈ allEffectSignatureCheckStatuses) := by
  exact ⟨EffectSignatureCheck_gap_kinds_complete, EffectSignatureCheck_statuses_complete⟩


-- Monitor-schema consistency for ct-api

/-- Gap kinds for CapabilitySetCtApi formalism. -/
inductive CapabilitySetCtApiGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetCtApi. -/
def allCapabilitySetCtApiGapKinds : List CapabilitySetCtApiGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetCtApi is accounted for. -/
theorem CapabilitySetCtApi_gap_kinds_complete :
    ∀ k : CapabilitySetCtApiGapKind, k ∈ allCapabilitySetCtApiGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetCtApiGapKinds]

/-- Gap statuses for CapabilitySetCtApi formalism. -/
inductive CapabilitySetCtApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetCtApi. -/
def allCapabilitySetCtApiStatuses : List CapabilitySetCtApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetCtApi is accounted for. -/
theorem CapabilitySetCtApi_statuses_complete :
    ∀ s : CapabilitySetCtApiStatus, s ∈ allCapabilitySetCtApiStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetCtApiStatuses]

/-- Monitor-schema consistency for CapabilitySetCtApi: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetCtApi_monitor_schema_consistent :
    (∀ k : CapabilitySetCtApiGapKind, k ∈ allCapabilitySetCtApiGapKinds) ∧
    (∀ s : CapabilitySetCtApiStatus, s ∈ allCapabilitySetCtApiStatuses) := by
  exact ⟨CapabilitySetCtApi_gap_kinds_complete, CapabilitySetCtApi_statuses_complete⟩


-- Monitor-schema consistency for ct-check

/-- Gap kinds for CapabilitySetCtCheck formalism. -/
inductive CapabilitySetCtCheckGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetCtCheck. -/
def allCapabilitySetCtCheckGapKinds : List CapabilitySetCtCheckGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetCtCheck is accounted for. -/
theorem CapabilitySetCtCheck_gap_kinds_complete :
    ∀ k : CapabilitySetCtCheckGapKind, k ∈ allCapabilitySetCtCheckGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetCtCheckGapKinds]

/-- Gap statuses for CapabilitySetCtCheck formalism. -/
inductive CapabilitySetCtCheckStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetCtCheck. -/
def allCapabilitySetCtCheckStatuses : List CapabilitySetCtCheckStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetCtCheck is accounted for. -/
theorem CapabilitySetCtCheck_statuses_complete :
    ∀ s : CapabilitySetCtCheckStatus, s ∈ allCapabilitySetCtCheckStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetCtCheckStatuses]

/-- Monitor-schema consistency for CapabilitySetCtCheck: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetCtCheck_monitor_schema_consistent :
    (∀ k : CapabilitySetCtCheckGapKind, k ∈ allCapabilitySetCtCheckGapKinds) ∧
    (∀ s : CapabilitySetCtCheckStatus, s ∈ allCapabilitySetCtCheckStatuses) := by
  exact ⟨CapabilitySetCtCheck_gap_kinds_complete, CapabilitySetCtCheck_statuses_complete⟩


-- Monitor-schema consistency for type-schema

/-- Gap kinds for TypeSchema formalism. -/
inductive TypeSchemaGapKind where
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for TypeSchema. -/
def allTypeSchemaGapKinds : List TypeSchemaGapKind :=
  [.unknown_type]

/-- Every gap kind for TypeSchema is accounted for. -/
theorem TypeSchema_gap_kinds_complete :
    ∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds := by
  intro k
  cases k <;> simp [allTypeSchemaGapKinds]

/-- Gap statuses for TypeSchema formalism. -/
inductive TypeSchemaStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for TypeSchema. -/
def allTypeSchemaStatuses : List TypeSchemaStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for TypeSchema is accounted for. -/
theorem TypeSchema_statuses_complete :
    ∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses := by
  intro s
  cases s <;> simp [allTypeSchemaStatuses]

/-- Monitor-schema consistency for TypeSchema: both gap-kind and status enumerations are exhaustive. -/
theorem TypeSchema_monitor_schema_consistent :
    (∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds) ∧
    (∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses) := by
  exact ⟨TypeSchema_gap_kinds_complete, TypeSchema_statuses_complete⟩

end ContainmentMonitorSchema
