namespace ContainmentRefExhaustive

-- Ref-extraction exhaustiveness verification
-- Generated by Pneuma

-- Ref-extraction exhaustiveness for api

/-- Ref-kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureApi. -/
def allEffectSignatureApiRefKinds : List EffectSignatureApiRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureApi. -/
theorem EffectSignatureApi_ref_exhaustive :
    ∀ k : EffectSignatureApiRefKind, k ∈ allEffectSignatureApiRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiRefKinds]


-- Ref-extraction exhaustiveness for check

/-- Ref-kinds for EffectSignatureCheck formalism. -/
inductive EffectSignatureCheckRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureCheck. -/
def allEffectSignatureCheckRefKinds : List EffectSignatureCheckRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureCheck. -/
theorem EffectSignatureCheck_ref_exhaustive :
    ∀ k : EffectSignatureCheckRefKind, k ∈ allEffectSignatureCheckRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureCheckRefKinds]


-- Ref-extraction exhaustiveness for ct-api

/-- Ref-kinds for CapabilitySetCtApi formalism. -/
inductive CapabilitySetCtApiRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetCtApi. -/
def allCapabilitySetCtApiRefKinds : List CapabilitySetCtApiRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetCtApi. -/
theorem CapabilitySetCtApi_ref_exhaustive :
    ∀ k : CapabilitySetCtApiRefKind, k ∈ allCapabilitySetCtApiRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetCtApiRefKinds]


-- Ref-extraction exhaustiveness for ct-check

/-- Ref-kinds for CapabilitySetCtCheck formalism. -/
inductive CapabilitySetCtCheckRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetCtCheck. -/
def allCapabilitySetCtCheckRefKinds : List CapabilitySetCtCheckRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetCtCheck. -/
theorem CapabilitySetCtCheck_ref_exhaustive :
    ∀ k : CapabilitySetCtCheckRefKind, k ∈ allCapabilitySetCtCheckRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetCtCheckRefKinds]


-- Ref-extraction exhaustiveness for type-schema

/-- Ref-kinds for TypeSchema formalism. -/
inductive TypeSchemaRefKind where
  | type_ids
  deriving DecidableEq, Repr

/-- All ref-kinds for TypeSchema. -/
def allTypeSchemaRefKinds : List TypeSchemaRefKind :=
  [.type_ids]

/-- extract-refs handles every ref-kind for TypeSchema. -/
theorem TypeSchema_ref_exhaustive :
    ∀ k : TypeSchemaRefKind, k ∈ allTypeSchemaRefKinds := by
  intro k
  cases k <;> simp [allTypeSchemaRefKinds]

end ContainmentRefExhaustive
