namespace CoreCircuits

-- Circuit verification for the morphism graph
-- Generated by Pneuma
-- Verifies Johnson's algorithm output for this concrete graph

/-- Adjacency function for the morphism graph.
    Returns true iff there exists a morphism from node a to node b. -/
def adj : Node → Node → Bool
  | .effect_signature_check, .type_schema => true
  | .effect_signature_constructors, .type_schema => true
  | .capability_set_core_check, .effect_signature_check => true
  | .capability_set_core_constructors, .effect_signature_constructors => true
  | .capability_set_core_gap, .effect_signature_gap => true
  | .effect_signature_gap, .type_schema => true
  | _, _ => false


/-- The graph contains exactly 0 elementary circuits. -/
def circuitCount : Nat := 0


-- No circuits discovered (acyclic graph)

end CoreCircuits
