-- Generated by Pneuma system-level ->lean projection
-- Source: Core
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque Any : Type := Unit
opaque Boolean : Type := Unit
opaque CapabilitySet : Type := Unit
opaque ComposedPathVec : Type := Unit
opaque ContainmentMorphism : Type := Unit
opaque DiffReport : Type := Unit
opaque EffectSignature : Type := Unit
opaque EventLog : Type := Unit
opaque ExistentialMorphism : Type := Unit
opaque Formalism : Type := Unit
opaque FormalismConfig : Type := Unit
opaque GapReport : Type := Unit
opaque GapReportConfig : Type := Unit
opaque GapVec : Type := Unit
opaque GenOpts : Type := Unit
opaque IConnection : Type := Unit
opaque IProjectable : Type := Unit
opaque Keyword : Type := Unit
opaque MealyHandlerSet : Type := Unit
opaque MorphismConfig : Type := Unit
opaque OpticDeclaration : Type := Unit
opaque OrderingMorphism : Type := Unit
opaque RefinementConfig : Type := Unit
opaque RefinementMap : Type := Unit
opaque Registry : Type := Unit
opaque ResolverGraph : Type := Unit
opaque Statechart : Type := Unit
opaque StructuralMorphism : Type := Unit
opaque TypeSchema : Type := Unit
opaque Verdict : Type := Unit

inductive Op where
  | capability_set
  | check_gen
  | check_morphism
  | check_schema
  | check_trace
  | containment_morphism
  | diff_reports
  | effect_signature
  | existential_morphism
  | failures
  | find_paths
  | gap_report
  | gaps_involving
  | has_changes?
  | has_failures?
  | mealy_handler_set
  | optic_declaration
  | ordering_morphism
  | refinement_map
  | resolver_graph
  | statechart
  | structural_morphism
  | type_schema
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.capability_set, .check_gen, .check_morphism, .check_schema, .check_trace, .containment_morphism, .diff_reports, .effect_signature, .existential_morphism, .failures, .find_paths, .gap_report, .gaps_involving, .has_changes?, .has_failures?, .mealy_handler_set, .optic_declaration, .ordering_morphism, .refinement_map, .resolver_graph, .statechart, .structural_morphism, .type_schema]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 23 := by
  rfl

def core_check_dispatch : List Op :=
  [.check_gen, .check_morphism, .check_schema, .check_trace]

def core_constructors_dispatch : List Op :=
  [.capability_set, .containment_morphism, .effect_signature, .existential_morphism, .mealy_handler_set, .optic_declaration, .ordering_morphism, .refinement_map, .resolver_graph, .statechart, .structural_morphism, .type_schema]

def core_gap_dispatch : List Op :=
  [.diff_reports, .failures, .find_paths, .gap_report, .gaps_involving, .has_changes?, .has_failures?]

-- Morphism check-caps->check-ops: core_check dispatch ⊆ allOps [conforms]
theorem core_check_dispatch_valid :
    ∀ op : Op, op ∈ core_check_dispatch → op ∈ allOps := by
  decide

-- Morphism constructor-caps->constructor-ops: core_constructors dispatch ⊆ allOps [conforms]
theorem core_constructors_dispatch_valid :
    ∀ op : Op, op ∈ core_constructors_dispatch → op ∈ allOps := by
  decide

-- Morphism gap-caps->gap-ops: core_gap dispatch ⊆ allOps [conforms]
theorem core_gap_dispatch_valid :
    ∀ op : Op, op ∈ core_gap_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ core_check_dispatch → op ∈ allOps) ∧
    (∀ op, op ∈ core_constructors_dispatch → op ∈ allOps) ∧
    (∀ op, op ∈ core_gap_dispatch → op ∈ allOps) := by
  exact ⟨core_check_dispatch_valid, core_constructors_dispatch_valid, core_gap_dispatch_valid⟩
