namespace CoreAlgebra

-- Morphism algebra for the specification graph
-- Generated by Pneuma

/-- Nodes of the morphism graph. Each node is a formalism kind. -/
inductive Node where
  | capability_set_core_check
  | capability_set_core_constructors
  | capability_set_core_gap
  | effect_signature_check
  | effect_signature_constructors
  | effect_signature_gap
  | type_schema
  deriving DecidableEq, Repr

/-- All nodes in the morphism graph. -/
def allNodes : List Node :=
  [.capability_set_core_check, .capability_set_core_constructors, .capability_set_core_gap, .effect_signature_check, .effect_signature_constructors, .effect_signature_gap, .type_schema]

/-- Every node appears in allNodes. -/
theorem allNodes_complete :
    ∀ n : Node, n ∈ allNodes := by
  intro n
  cases n <;> simp [allNodes]

/-- allNodes contains exactly 7 members. -/
theorem allNodes_count :
    allNodes.length = 7 := by
  rfl

/-- Edges of the morphism graph. Each edge is a morphism. -/
inductive Edge where
  | check_caps__check_ops
  | check_ops__types
  | constructor_caps__constructor_ops
  | constructor_ops__types
  | gap_caps__gap_ops
  | gap_ops__types
  deriving DecidableEq, Repr

/-- All edges in the morphism graph. -/
def allEdges : List Edge :=
  [.check_caps__check_ops, .check_ops__types, .constructor_caps__constructor_ops, .constructor_ops__types, .gap_caps__gap_ops, .gap_ops__types]

/-- Every edge appears in allEdges. -/
theorem allEdges_complete :
    ∀ e : Edge, e ∈ allEdges := by
  intro e
  cases e <;> simp [allEdges]

/-- Maps each edge to its source node. -/
def edgeSource : Edge → Node
  | .check_caps__check_ops => .capability_set_core_check
  | .check_ops__types => .effect_signature_check
  | .constructor_caps__constructor_ops => .capability_set_core_constructors
  | .constructor_ops__types => .effect_signature_constructors
  | .gap_caps__gap_ops => .capability_set_core_gap
  | .gap_ops__types => .effect_signature_gap

/-- Maps each edge to its target node. -/
def edgeTarget : Edge → Node
  | .check_caps__check_ops => .effect_signature_check
  | .check_ops__types => .type_schema
  | .constructor_caps__constructor_ops => .effect_signature_constructors
  | .constructor_ops__types => .type_schema
  | .gap_caps__gap_ops => .effect_signature_gap
  | .gap_ops__types => .type_schema

/-- Two edges are composable when the first's target equals the second's source. -/
def composable (e1 e2 : Edge) : Bool :=
  edgeTarget e1 == edgeSource e2

/-- Reflexivity: edgeSource and edgeTarget are well-defined for every edge. -/
theorem edge_endpoints_defined :
    ∀ e : Edge, edgeSource e ∈ allNodes ∧ edgeTarget e ∈ allNodes := by
  intro e
  cases e <;> simp [edgeSource, edgeTarget, allNodes]

/-- Composition associativity: if e1;e2 and e2;e3 compose, then grouping is irrelevant. -/
theorem composable_assoc :
    ∀ e1 e2 e3 : Edge,
      composable e1 e2 = true → composable e2 e3 = true →
      (edgeTarget e1 == edgeSource e2) = true ∧
      (edgeTarget e2 == edgeSource e3) = true := by
  decide

/-- Composable edges share a common interior node: target of e1 = source of e2. -/
theorem composable_shared_node :
    ∀ e1 e2 : Edge,
      composable e1 e2 = true →
      edgeTarget e1 = edgeSource e2 := by
  intro e1 e2 h
  simp [composable] at h
  exact beq_iff_eq.mp h

end CoreAlgebra
