namespace EffectSignatureMonitorSchema

-- Monitor-schema consistency verification
-- Generated by Pneuma

-- Monitor-schema consistency for api

/-- Gap kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureApi. -/
def allEffectSignatureApiGapKinds : List EffectSignatureApiGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_gap_kinds_complete :
    ∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiGapKinds]

/-- Gap statuses for EffectSignatureApi formalism. -/
inductive EffectSignatureApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureApi. -/
def allEffectSignatureApiStatuses : List EffectSignatureApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_statuses_complete :
    ∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureApiStatuses]

/-- Monitor-schema consistency for EffectSignatureApi: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureApi_monitor_schema_consistent :
    (∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds) ∧
    (∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses) := by
  exact ⟨EffectSignatureApi_gap_kinds_complete, EffectSignatureApi_statuses_complete⟩


-- Monitor-schema consistency for es-api

/-- Gap kinds for CapabilitySetEsApi formalism. -/
inductive CapabilitySetEsApiGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetEsApi. -/
def allCapabilitySetEsApiGapKinds : List CapabilitySetEsApiGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetEsApi is accounted for. -/
theorem CapabilitySetEsApi_gap_kinds_complete :
    ∀ k : CapabilitySetEsApiGapKind, k ∈ allCapabilitySetEsApiGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetEsApiGapKinds]

/-- Gap statuses for CapabilitySetEsApi formalism. -/
inductive CapabilitySetEsApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetEsApi. -/
def allCapabilitySetEsApiStatuses : List CapabilitySetEsApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetEsApi is accounted for. -/
theorem CapabilitySetEsApi_statuses_complete :
    ∀ s : CapabilitySetEsApiStatus, s ∈ allCapabilitySetEsApiStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetEsApiStatuses]

/-- Monitor-schema consistency for CapabilitySetEsApi: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetEsApi_monitor_schema_consistent :
    (∀ k : CapabilitySetEsApiGapKind, k ∈ allCapabilitySetEsApiGapKinds) ∧
    (∀ s : CapabilitySetEsApiStatus, s ∈ allCapabilitySetEsApiStatuses) := by
  exact ⟨CapabilitySetEsApi_gap_kinds_complete, CapabilitySetEsApi_statuses_complete⟩


-- Monitor-schema consistency for es-ref-kinds

/-- Gap kinds for CapabilitySetEsRefKinds formalism. -/
inductive CapabilitySetEsRefKindsGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetEsRefKinds. -/
def allCapabilitySetEsRefKindsGapKinds : List CapabilitySetEsRefKindsGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetEsRefKinds is accounted for. -/
theorem CapabilitySetEsRefKinds_gap_kinds_complete :
    ∀ k : CapabilitySetEsRefKindsGapKind, k ∈ allCapabilitySetEsRefKindsGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetEsRefKindsGapKinds]

/-- Gap statuses for CapabilitySetEsRefKinds formalism. -/
inductive CapabilitySetEsRefKindsStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetEsRefKinds. -/
def allCapabilitySetEsRefKindsStatuses : List CapabilitySetEsRefKindsStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetEsRefKinds is accounted for. -/
theorem CapabilitySetEsRefKinds_statuses_complete :
    ∀ s : CapabilitySetEsRefKindsStatus, s ∈ allCapabilitySetEsRefKindsStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetEsRefKindsStatuses]

/-- Monitor-schema consistency for CapabilitySetEsRefKinds: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetEsRefKinds_monitor_schema_consistent :
    (∀ k : CapabilitySetEsRefKindsGapKind, k ∈ allCapabilitySetEsRefKindsGapKinds) ∧
    (∀ s : CapabilitySetEsRefKindsStatus, s ∈ allCapabilitySetEsRefKindsStatuses) := by
  exact ⟨CapabilitySetEsRefKinds_gap_kinds_complete, CapabilitySetEsRefKinds_statuses_complete⟩


-- Monitor-schema consistency for refs

/-- Gap kinds for EffectSignatureRefs formalism. -/
inductive EffectSignatureRefsGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureRefs. -/
def allEffectSignatureRefsGapKinds : List EffectSignatureRefsGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureRefs is accounted for. -/
theorem EffectSignatureRefs_gap_kinds_complete :
    ∀ k : EffectSignatureRefsGapKind, k ∈ allEffectSignatureRefsGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureRefsGapKinds]

/-- Gap statuses for EffectSignatureRefs formalism. -/
inductive EffectSignatureRefsStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureRefs. -/
def allEffectSignatureRefsStatuses : List EffectSignatureRefsStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureRefs is accounted for. -/
theorem EffectSignatureRefs_statuses_complete :
    ∀ s : EffectSignatureRefsStatus, s ∈ allEffectSignatureRefsStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureRefsStatuses]

/-- Monitor-schema consistency for EffectSignatureRefs: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureRefs_monitor_schema_consistent :
    (∀ k : EffectSignatureRefsGapKind, k ∈ allEffectSignatureRefsGapKinds) ∧
    (∀ s : EffectSignatureRefsStatus, s ∈ allEffectSignatureRefsStatuses) := by
  exact ⟨EffectSignatureRefs_gap_kinds_complete, EffectSignatureRefs_statuses_complete⟩


-- Monitor-schema consistency for type-schema

/-- Gap kinds for TypeSchema formalism. -/
inductive TypeSchemaGapKind where
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for TypeSchema. -/
def allTypeSchemaGapKinds : List TypeSchemaGapKind :=
  [.unknown_type]

/-- Every gap kind for TypeSchema is accounted for. -/
theorem TypeSchema_gap_kinds_complete :
    ∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds := by
  intro k
  cases k <;> simp [allTypeSchemaGapKinds]

/-- Gap statuses for TypeSchema formalism. -/
inductive TypeSchemaStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for TypeSchema. -/
def allTypeSchemaStatuses : List TypeSchemaStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for TypeSchema is accounted for. -/
theorem TypeSchema_statuses_complete :
    ∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses := by
  intro s
  cases s <;> simp [allTypeSchemaStatuses]

/-- Monitor-schema consistency for TypeSchema: both gap-kind and status enumerations are exhaustive. -/
theorem TypeSchema_monitor_schema_consistent :
    (∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds) ∧
    (∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses) := by
  exact ⟨TypeSchema_gap_kinds_complete, TypeSchema_statuses_complete⟩

end EffectSignatureMonitorSchema
