-- Generated by Pneuma system-level ->lean projection
-- Source: EffectSignature
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque EffectSignature : Type := Unit
opaque Keyword : Type := Unit
opaque KeywordSet : Type := Unit
opaque MalliSchema : Type := Unit
opaque Nil : Type := Unit
opaque OperationsMap : Type := Unit

inductive Op where
  | callback_refs
  | effect_signature
  | operation_ids
  | operation_outputs
  | register_type!
  | resolve_type
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.callback_refs, .effect_signature, .operation_ids, .operation_outputs, .register_type!, .resolve_type]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 6 := by
  rfl

def es_api_dispatch : List Op :=
  [.effect_signature, .register_type!, .resolve_type]

def es_ref_kinds_dispatch : List Op :=
  [.callback_refs, .operation_ids, .operation_outputs]

-- Morphism api-caps->api-ops: es_api dispatch ⊆ allOps [conforms]
theorem es_api_dispatch_valid :
    ∀ op : Op, op ∈ es_api_dispatch → op ∈ allOps := by
  decide

-- Morphism ref-kind-caps->ref-ops: es_ref_kinds dispatch ⊆ allOps [conforms]
theorem es_ref_kinds_dispatch_valid :
    ∀ op : Op, op ∈ es_ref_kinds_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ es_api_dispatch → op ∈ allOps) ∧
    (∀ op, op ∈ es_ref_kinds_dispatch → op ∈ allOps) := by
  exact ⟨es_api_dispatch_valid, es_ref_kinds_dispatch_valid⟩
