namespace EffectSignatureRefExhaustive

-- Ref-extraction exhaustiveness verification
-- Generated by Pneuma

-- Ref-extraction exhaustiveness for api

/-- Ref-kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureApi. -/
def allEffectSignatureApiRefKinds : List EffectSignatureApiRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureApi. -/
theorem EffectSignatureApi_ref_exhaustive :
    ∀ k : EffectSignatureApiRefKind, k ∈ allEffectSignatureApiRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiRefKinds]


-- Ref-extraction exhaustiveness for es-api

/-- Ref-kinds for CapabilitySetEsApi formalism. -/
inductive CapabilitySetEsApiRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetEsApi. -/
def allCapabilitySetEsApiRefKinds : List CapabilitySetEsApiRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetEsApi. -/
theorem CapabilitySetEsApi_ref_exhaustive :
    ∀ k : CapabilitySetEsApiRefKind, k ∈ allCapabilitySetEsApiRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetEsApiRefKinds]


-- Ref-extraction exhaustiveness for es-ref-kinds

/-- Ref-kinds for CapabilitySetEsRefKinds formalism. -/
inductive CapabilitySetEsRefKindsRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetEsRefKinds. -/
def allCapabilitySetEsRefKindsRefKinds : List CapabilitySetEsRefKindsRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetEsRefKinds. -/
theorem CapabilitySetEsRefKinds_ref_exhaustive :
    ∀ k : CapabilitySetEsRefKindsRefKind, k ∈ allCapabilitySetEsRefKindsRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetEsRefKindsRefKinds]


-- Ref-extraction exhaustiveness for refs

/-- Ref-kinds for EffectSignatureRefs formalism. -/
inductive EffectSignatureRefsRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureRefs. -/
def allEffectSignatureRefsRefKinds : List EffectSignatureRefsRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureRefs. -/
theorem EffectSignatureRefs_ref_exhaustive :
    ∀ k : EffectSignatureRefsRefKind, k ∈ allEffectSignatureRefsRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureRefsRefKinds]


-- Ref-extraction exhaustiveness for type-schema

/-- Ref-kinds for TypeSchema formalism. -/
inductive TypeSchemaRefKind where
  | type_ids
  deriving DecidableEq, Repr

/-- All ref-kinds for TypeSchema. -/
def allTypeSchemaRefKinds : List TypeSchemaRefKind :=
  [.type_ids]

/-- extract-refs handles every ref-kind for TypeSchema. -/
theorem TypeSchema_ref_exhaustive :
    ∀ k : TypeSchemaRefKind, k ∈ allTypeSchemaRefKinds := by
  intro k
  cases k <;> simp [allTypeSchemaRefKinds]

end EffectSignatureRefExhaustive
