-- Generated by Pneuma system-level ->lean projection
-- Source: Existential
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque ExistentialMorphism : Type := Unit
opaque GapSeq : Type := Unit
opaque IReferenceable : Type := Unit
opaque Keyword : Type := Unit
opaque RefinementMap : Type := Unit

inductive Op where
  | check
  | existential_morphism
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.check, .existential_morphism]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 2 := by
  rfl

def ex_api_dispatch : List Op :=
  [.existential_morphism]

def ex_check_dispatch : List Op :=
  [.check]

-- Morphism api-caps->api-ops: ex_api dispatch ⊆ allOps [conforms]
theorem ex_api_dispatch_valid :
    ∀ op : Op, op ∈ ex_api_dispatch → op ∈ allOps := by
  decide

-- Morphism check-caps->check-ops: ex_check dispatch ⊆ allOps [conforms]
theorem ex_check_dispatch_valid :
    ∀ op : Op, op ∈ ex_check_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ ex_api_dispatch → op ∈ allOps) ∧
    (∀ op, op ∈ ex_check_dispatch → op ∈ allOps) := by
  exact ⟨ex_api_dispatch_valid, ex_check_dispatch_valid⟩
