namespace ExistentialRefExhaustive

-- Ref-extraction exhaustiveness verification
-- Generated by Pneuma

-- Ref-extraction exhaustiveness for api

/-- Ref-kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureApi. -/
def allEffectSignatureApiRefKinds : List EffectSignatureApiRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureApi. -/
theorem EffectSignatureApi_ref_exhaustive :
    ∀ k : EffectSignatureApiRefKind, k ∈ allEffectSignatureApiRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiRefKinds]


-- Ref-extraction exhaustiveness for check

/-- Ref-kinds for EffectSignatureCheck formalism. -/
inductive EffectSignatureCheckRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureCheck. -/
def allEffectSignatureCheckRefKinds : List EffectSignatureCheckRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureCheck. -/
theorem EffectSignatureCheck_ref_exhaustive :
    ∀ k : EffectSignatureCheckRefKind, k ∈ allEffectSignatureCheckRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureCheckRefKinds]


-- Ref-extraction exhaustiveness for ex-api

/-- Ref-kinds for CapabilitySetExApi formalism. -/
inductive CapabilitySetExApiRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetExApi. -/
def allCapabilitySetExApiRefKinds : List CapabilitySetExApiRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetExApi. -/
theorem CapabilitySetExApi_ref_exhaustive :
    ∀ k : CapabilitySetExApiRefKind, k ∈ allCapabilitySetExApiRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetExApiRefKinds]


-- Ref-extraction exhaustiveness for ex-check

/-- Ref-kinds for CapabilitySetExCheck formalism. -/
inductive CapabilitySetExCheckRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetExCheck. -/
def allCapabilitySetExCheckRefKinds : List CapabilitySetExCheckRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetExCheck. -/
theorem CapabilitySetExCheck_ref_exhaustive :
    ∀ k : CapabilitySetExCheckRefKind, k ∈ allCapabilitySetExCheckRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetExCheckRefKinds]


-- Ref-extraction exhaustiveness for type-schema

/-- Ref-kinds for TypeSchema formalism. -/
inductive TypeSchemaRefKind where
  | type_ids
  deriving DecidableEq, Repr

/-- All ref-kinds for TypeSchema. -/
def allTypeSchemaRefKinds : List TypeSchemaRefKind :=
  [.type_ids]

/-- extract-refs handles every ref-kind for TypeSchema. -/
theorem TypeSchema_ref_exhaustive :
    ∀ k : TypeSchemaRefKind, k ∈ allTypeSchemaRefKinds := by
  intro k
  cases k <;> simp [allTypeSchemaRefKinds]

end ExistentialRefExhaustive
