namespace ExistentialMonitorSchema

-- Monitor-schema consistency verification
-- Generated by Pneuma

-- Monitor-schema consistency for api

/-- Gap kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureApi. -/
def allEffectSignatureApiGapKinds : List EffectSignatureApiGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_gap_kinds_complete :
    ∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiGapKinds]

/-- Gap statuses for EffectSignatureApi formalism. -/
inductive EffectSignatureApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureApi. -/
def allEffectSignatureApiStatuses : List EffectSignatureApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_statuses_complete :
    ∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureApiStatuses]

/-- Monitor-schema consistency for EffectSignatureApi: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureApi_monitor_schema_consistent :
    (∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds) ∧
    (∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses) := by
  exact ⟨EffectSignatureApi_gap_kinds_complete, EffectSignatureApi_statuses_complete⟩


-- Monitor-schema consistency for check

/-- Gap kinds for EffectSignatureCheck formalism. -/
inductive EffectSignatureCheckGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureCheck. -/
def allEffectSignatureCheckGapKinds : List EffectSignatureCheckGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureCheck is accounted for. -/
theorem EffectSignatureCheck_gap_kinds_complete :
    ∀ k : EffectSignatureCheckGapKind, k ∈ allEffectSignatureCheckGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureCheckGapKinds]

/-- Gap statuses for EffectSignatureCheck formalism. -/
inductive EffectSignatureCheckStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureCheck. -/
def allEffectSignatureCheckStatuses : List EffectSignatureCheckStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureCheck is accounted for. -/
theorem EffectSignatureCheck_statuses_complete :
    ∀ s : EffectSignatureCheckStatus, s ∈ allEffectSignatureCheckStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureCheckStatuses]

/-- Monitor-schema consistency for EffectSignatureCheck: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureCheck_monitor_schema_consistent :
    (∀ k : EffectSignatureCheckGapKind, k ∈ allEffectSignatureCheckGapKinds) ∧
    (∀ s : EffectSignatureCheckStatus, s ∈ allEffectSignatureCheckStatuses) := by
  exact ⟨EffectSignatureCheck_gap_kinds_complete, EffectSignatureCheck_statuses_complete⟩


-- Monitor-schema consistency for ex-api

/-- Gap kinds for CapabilitySetExApi formalism. -/
inductive CapabilitySetExApiGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetExApi. -/
def allCapabilitySetExApiGapKinds : List CapabilitySetExApiGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetExApi is accounted for. -/
theorem CapabilitySetExApi_gap_kinds_complete :
    ∀ k : CapabilitySetExApiGapKind, k ∈ allCapabilitySetExApiGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetExApiGapKinds]

/-- Gap statuses for CapabilitySetExApi formalism. -/
inductive CapabilitySetExApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetExApi. -/
def allCapabilitySetExApiStatuses : List CapabilitySetExApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetExApi is accounted for. -/
theorem CapabilitySetExApi_statuses_complete :
    ∀ s : CapabilitySetExApiStatus, s ∈ allCapabilitySetExApiStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetExApiStatuses]

/-- Monitor-schema consistency for CapabilitySetExApi: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetExApi_monitor_schema_consistent :
    (∀ k : CapabilitySetExApiGapKind, k ∈ allCapabilitySetExApiGapKinds) ∧
    (∀ s : CapabilitySetExApiStatus, s ∈ allCapabilitySetExApiStatuses) := by
  exact ⟨CapabilitySetExApi_gap_kinds_complete, CapabilitySetExApi_statuses_complete⟩


-- Monitor-schema consistency for ex-check

/-- Gap kinds for CapabilitySetExCheck formalism. -/
inductive CapabilitySetExCheckGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetExCheck. -/
def allCapabilitySetExCheckGapKinds : List CapabilitySetExCheckGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetExCheck is accounted for. -/
theorem CapabilitySetExCheck_gap_kinds_complete :
    ∀ k : CapabilitySetExCheckGapKind, k ∈ allCapabilitySetExCheckGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetExCheckGapKinds]

/-- Gap statuses for CapabilitySetExCheck formalism. -/
inductive CapabilitySetExCheckStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetExCheck. -/
def allCapabilitySetExCheckStatuses : List CapabilitySetExCheckStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetExCheck is accounted for. -/
theorem CapabilitySetExCheck_statuses_complete :
    ∀ s : CapabilitySetExCheckStatus, s ∈ allCapabilitySetExCheckStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetExCheckStatuses]

/-- Monitor-schema consistency for CapabilitySetExCheck: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetExCheck_monitor_schema_consistent :
    (∀ k : CapabilitySetExCheckGapKind, k ∈ allCapabilitySetExCheckGapKinds) ∧
    (∀ s : CapabilitySetExCheckStatus, s ∈ allCapabilitySetExCheckStatuses) := by
  exact ⟨CapabilitySetExCheck_gap_kinds_complete, CapabilitySetExCheck_statuses_complete⟩


-- Monitor-schema consistency for type-schema

/-- Gap kinds for TypeSchema formalism. -/
inductive TypeSchemaGapKind where
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for TypeSchema. -/
def allTypeSchemaGapKinds : List TypeSchemaGapKind :=
  [.unknown_type]

/-- Every gap kind for TypeSchema is accounted for. -/
theorem TypeSchema_gap_kinds_complete :
    ∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds := by
  intro k
  cases k <;> simp [allTypeSchemaGapKinds]

/-- Gap statuses for TypeSchema formalism. -/
inductive TypeSchemaStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for TypeSchema. -/
def allTypeSchemaStatuses : List TypeSchemaStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for TypeSchema is accounted for. -/
theorem TypeSchema_statuses_complete :
    ∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses := by
  intro s
  cases s <;> simp [allTypeSchemaStatuses]

/-- Monitor-schema consistency for TypeSchema: both gap-kind and status enumerations are exhaustive. -/
theorem TypeSchema_monitor_schema_consistent :
    (∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds) ∧
    (∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses) := by
  exact ⟨TypeSchema_gap_kinds_complete, TypeSchema_statuses_complete⟩

end ExistentialMonitorSchema
