-- Generated by Pneuma system-level ->lean projection
-- Source: GapCore
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque Boolean : Type := Unit
opaque FormalismMap : Type := Unit
opaque GapReport : Type := Unit
opaque GapReportConfig : Type := Unit
opaque GapVec : Type := Unit
opaque IProjectable : Type := Unit
opaque Registry : Type := Unit

inductive Op where
  | check_morphism_gaps
  | check_object_gaps
  | failures
  | gap_report
  | has_failures?
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.check_morphism_gaps, .check_object_gaps, .failures, .gap_report, .has_failures?]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 5 := by
  rfl

def gap_api_dispatch : List Op :=
  [.check_morphism_gaps, .check_object_gaps, .failures, .gap_report, .has_failures?]

-- Morphism api-caps->api-ops: gap_api dispatch ⊆ allOps [conforms]
theorem gap_api_dispatch_valid :
    ∀ op : Op, op ∈ gap_api_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ gap_api_dispatch → op ∈ allOps) := by
  exact ⟨gap_api_dispatch_valid⟩
