-- Generated by Pneuma system-level ->lean projection
-- Source: GapDiff
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque Boolean : Type := Unit
opaque DiffReport : Type := Unit
opaque GapReport : Type := Unit
opaque Keyword : Type := Unit

inductive Op where
  | diff_reports
  | gaps_involving
  | has_changes?
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.diff_reports, .gaps_involving, .has_changes?]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 3 := by
  rfl

def diff_api_dispatch : List Op :=
  [.diff_reports, .gaps_involving, .has_changes?]

-- Morphism api-caps->api-ops: diff_api dispatch ⊆ allOps [conforms]
theorem diff_api_dispatch_valid :
    ∀ op : Op, op ∈ diff_api_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ diff_api_dispatch → op ∈ allOps) := by
  exact ⟨diff_api_dispatch_valid⟩
