-- Generated by Pneuma system-level ->lean projection
-- Source: Lean
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque Formalism : Type := Unit
opaque LeanSource : Type := Unit
opaque Morphism : Type := Unit

inductive Op where
  | lean
  | lean_conn
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.lean, .lean_conn]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 2 := by
  rfl

def lean_formalism_dispatch : List Op :=
  [.lean]

def lean_morphism_dispatch : List Op :=
  [.lean_conn]

-- Morphism lean-formalism-caps->ops: lean_formalism dispatch ⊆ allOps [conforms]
theorem lean_formalism_dispatch_valid :
    ∀ op : Op, op ∈ lean_formalism_dispatch → op ∈ allOps := by
  decide

-- Morphism lean-morphism-caps->ops: lean_morphism dispatch ⊆ allOps [conforms]
theorem lean_morphism_dispatch_valid :
    ∀ op : Op, op ∈ lean_morphism_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ lean_formalism_dispatch → op ∈ allOps) ∧
    (∀ op, op ∈ lean_morphism_dispatch → op ∈ allOps) := by
  exact ⟨lean_formalism_dispatch_valid, lean_morphism_dispatch_valid⟩
