-- Generated by Pneuma system-level ->lean projection
-- Source: LeanCore
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque ComposedPath : Type := Unit
opaque EmissionMap : Type := Unit
opaque Formalism : Type := Unit
opaque FormalismMap : Type := Unit
opaque ILeanConnection : Type := Unit
opaque ILeanProjectable : Type := Unit
opaque LeanSource : Type := Unit
opaque PathResultVec : Type := Unit
opaque Registry : Type := Unit
opaque SectionVec : Type := Unit
opaque SystemConfig : Type := Unit

inductive Op where
  | emit_lean
  | emit_lean_all
  | emit_lean_conn
  | emit_lean_file
  | emit_lean_path
  | emit_lean_paths
  | emit_lean_system
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.emit_lean, .emit_lean_all, .emit_lean_conn, .emit_lean_file, .emit_lean_path, .emit_lean_paths, .emit_lean_system]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 7 := by
  rfl

def lean_core_dispatch : List Op :=
  [.emit_lean, .emit_lean_all, .emit_lean_conn, .emit_lean_file, .emit_lean_path, .emit_lean_paths, .emit_lean_system]

-- Morphism caps->ops: lean_core dispatch ⊆ allOps [conforms]
theorem lean_core_dispatch_valid :
    ∀ op : Op, op ∈ lean_core_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ lean_core_dispatch → op ∈ allOps) := by
  exact ⟨lean_core_dispatch_valid⟩
