-- Generated by Pneuma system-level ->lean projection
-- Source: LeanEffectSig
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

/-- Opaque proxy for domain type :EffectSignature. -/
opaque EffectSignature : Type := Unit
/-- Opaque proxy for domain type :LeanSource. -/
opaque LeanSource : Type := Unit

/-- Operation alphabet for system specification LeanEffectSig. -/
inductive Op where
  | lean
  deriving DecidableEq, Repr

/-- Exhaustive list of all operations in the system specification. -/
def allOps : List Op :=
  [.lean]

/-- Every member of Op appears in allOps. Proved by case analysis. -/
theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

/-- allOps contains exactly 1 members. -/
theorem allOps_count :
    allOps.length = 1 := by
  rfl

/-- Dispatch operations permitted by capability set :lean-es. -/
def lean_es_dispatch : List Op :=
  [.lean]

-- Morphism caps->ops: lean_es dispatch ⊆ allOps [conforms]
/-- All dispatch operations of :lean-es are valid members of Op. -/
theorem lean_es_dispatch_valid :
    ∀ op : Op, op ∈ lean_es_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
/-- All capability dispatch sets reference valid operations in the effect signature. -/
theorem system_conformance :
    (∀ op, op ∈ lean_es_dispatch → op ∈ allOps) := by
  -- lean_es dispatch is valid
  have h1 := lean_es_dispatch_valid
  exact ⟨h1⟩
