namespace LeanMealyGapComplete

-- Gap report completeness verification
-- Generated by Pneuma

/-- All morphism identifiers in the registry. -/
inductive MorphismId where
  | caps__ops
  | ops__types
  deriving DecidableEq, Repr

/-- Morphism ids that were checked in the gap report. -/
def checkedMorphisms : List MorphismId :=
  [.caps__ops, .ops__types]

/-- Every registered morphism was checked in the gap report. -/
theorem morphism_gap_complete :
    ∀ m : MorphismId, m ∈ checkedMorphisms := by
  intro m
  cases m <;> simp [checkedMorphisms]

/-- All formalism kinds in the specification. -/
inductive FormalismKind where
  | capability_set_lean_mealy
  | effect_signature_api
  | type_schema
  deriving DecidableEq, Repr

/-- Formalism kinds that were checked at the object layer. -/
def checkedFormalisms : List FormalismKind :=
  [.capability_set, .effect_signature, .type_schema]

/-- Every formalism kind was checked at the object layer. -/
theorem object_gap_complete :
    ∀ f : FormalismKind, f ∈ checkedFormalisms := by
  intro f
  cases f <;> simp [checkedFormalisms]

/-- The gap report checked every registered component at every layer. -/
theorem gap_report_complete :
    (∀ m : MorphismId, m ∈ checkedMorphisms) ∧
    (∀ f : FormalismKind, f ∈ checkedFormalisms) := by
  exact ⟨morphism_gap_complete, object_gap_complete⟩

end LeanMealyGapComplete
