namespace LeanEffectSigMonitorSchema

-- Monitor-schema consistency verification
-- Generated by Pneuma

-- Monitor-schema consistency for api

/-- Gap kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureApi. -/
def allEffectSignatureApiGapKinds : List EffectSignatureApiGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_gap_kinds_complete :
    ∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiGapKinds]

/-- Gap statuses for EffectSignatureApi formalism. -/
inductive EffectSignatureApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureApi. -/
def allEffectSignatureApiStatuses : List EffectSignatureApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_statuses_complete :
    ∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureApiStatuses]

/-- Monitor-schema consistency for EffectSignatureApi: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureApi_monitor_schema_consistent :
    (∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds) ∧
    (∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses) := by
  exact ⟨EffectSignatureApi_gap_kinds_complete, EffectSignatureApi_statuses_complete⟩


-- Monitor-schema consistency for lean-es

/-- Gap kinds for CapabilitySetLeanEs formalism. -/
inductive CapabilitySetLeanEsGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetLeanEs. -/
def allCapabilitySetLeanEsGapKinds : List CapabilitySetLeanEsGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetLeanEs is accounted for. -/
theorem CapabilitySetLeanEs_gap_kinds_complete :
    ∀ k : CapabilitySetLeanEsGapKind, k ∈ allCapabilitySetLeanEsGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetLeanEsGapKinds]

/-- Gap statuses for CapabilitySetLeanEs formalism. -/
inductive CapabilitySetLeanEsStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetLeanEs. -/
def allCapabilitySetLeanEsStatuses : List CapabilitySetLeanEsStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetLeanEs is accounted for. -/
theorem CapabilitySetLeanEs_statuses_complete :
    ∀ s : CapabilitySetLeanEsStatus, s ∈ allCapabilitySetLeanEsStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetLeanEsStatuses]

/-- Monitor-schema consistency for CapabilitySetLeanEs: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetLeanEs_monitor_schema_consistent :
    (∀ k : CapabilitySetLeanEsGapKind, k ∈ allCapabilitySetLeanEsGapKinds) ∧
    (∀ s : CapabilitySetLeanEsStatus, s ∈ allCapabilitySetLeanEsStatuses) := by
  exact ⟨CapabilitySetLeanEs_gap_kinds_complete, CapabilitySetLeanEs_statuses_complete⟩


-- Monitor-schema consistency for type-schema

/-- Gap kinds for TypeSchema formalism. -/
inductive TypeSchemaGapKind where
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for TypeSchema. -/
def allTypeSchemaGapKinds : List TypeSchemaGapKind :=
  [.unknown_type]

/-- Every gap kind for TypeSchema is accounted for. -/
theorem TypeSchema_gap_kinds_complete :
    ∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds := by
  intro k
  cases k <;> simp [allTypeSchemaGapKinds]

/-- Gap statuses for TypeSchema formalism. -/
inductive TypeSchemaStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for TypeSchema. -/
def allTypeSchemaStatuses : List TypeSchemaStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for TypeSchema is accounted for. -/
theorem TypeSchema_statuses_complete :
    ∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses := by
  intro s
  cases s <;> simp [allTypeSchemaStatuses]

/-- Monitor-schema consistency for TypeSchema: both gap-kind and status enumerations are exhaustive. -/
theorem TypeSchema_monitor_schema_consistent :
    (∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds) ∧
    (∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses) := by
  exact ⟨TypeSchema_gap_kinds_complete, TypeSchema_statuses_complete⟩

end LeanEffectSigMonitorSchema
