-- Generated by Pneuma system-level ->lean projection
-- Source: LeanOrdering
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque IReferenceable : Type := Unit
opaque LeanSource : Type := Unit
opaque OrderingMorphism : Type := Unit

inductive Op where
  | lean_conn
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.lean_conn]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 1 := by
  rfl

def lean_ord_dispatch : List Op :=
  [.lean_conn]

-- Morphism caps->ops: lean_ord dispatch ⊆ allOps [conforms]
theorem lean_ord_dispatch_valid :
    ∀ op : Op, op ∈ lean_ord_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ lean_ord_dispatch → op ∈ allOps) := by
  exact ⟨lean_ord_dispatch_valid⟩
