namespace LeanCoreRefExhaustive

-- Ref-extraction exhaustiveness verification
-- Generated by Pneuma

-- Ref-extraction exhaustiveness for api

/-- Ref-kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureApi. -/
def allEffectSignatureApiRefKinds : List EffectSignatureApiRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureApi. -/
theorem EffectSignatureApi_ref_exhaustive :
    ∀ k : EffectSignatureApiRefKind, k ∈ allEffectSignatureApiRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiRefKinds]


-- Ref-extraction exhaustiveness for lean-core

/-- Ref-kinds for CapabilitySetLeanCore formalism. -/
inductive CapabilitySetLeanCoreRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetLeanCore. -/
def allCapabilitySetLeanCoreRefKinds : List CapabilitySetLeanCoreRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetLeanCore. -/
theorem CapabilitySetLeanCore_ref_exhaustive :
    ∀ k : CapabilitySetLeanCoreRefKind, k ∈ allCapabilitySetLeanCoreRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetLeanCoreRefKinds]


-- Ref-extraction exhaustiveness for type-schema

/-- Ref-kinds for TypeSchema formalism. -/
inductive TypeSchemaRefKind where
  | type_ids
  deriving DecidableEq, Repr

/-- All ref-kinds for TypeSchema. -/
def allTypeSchemaRefKinds : List TypeSchemaRefKind :=
  [.type_ids]

/-- extract-refs handles every ref-kind for TypeSchema. -/
theorem TypeSchema_ref_exhaustive :
    ∀ k : TypeSchemaRefKind, k ∈ allTypeSchemaRefKinds := by
  intro k
  cases k <;> simp [allTypeSchemaRefKinds]

end LeanCoreRefExhaustive
