-- Generated by Pneuma system-level ->lean projection
-- Source: LeanOrdering
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

/-- Opaque proxy for domain type :IReferenceable. -/
opaque IReferenceable : Type := Unit
/-- Opaque proxy for domain type :LeanSource. -/
opaque LeanSource : Type := Unit
/-- Opaque proxy for domain type :OrderingMorphism. -/
opaque OrderingMorphism : Type := Unit

/-- Operation alphabet for system specification LeanOrdering. -/
inductive Op where
  | lean_conn
  deriving DecidableEq, Repr

/-- Exhaustive list of all operations in the system specification. -/
def allOps : List Op :=
  [.lean_conn]

/-- Every member of Op appears in allOps. Proved by case analysis. -/
theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

/-- allOps contains exactly 1 members. -/
theorem allOps_count :
    allOps.length = 1 := by
  rfl

/-- Dispatch operations permitted by capability set :lean-ord. -/
def lean_ord_dispatch : List Op :=
  [.lean_conn]

-- Morphism caps->ops: lean_ord dispatch ⊆ allOps [conforms]
/-- All dispatch operations of :lean-ord are valid members of Op. -/
theorem lean_ord_dispatch_valid :
    ∀ op : Op, op ∈ lean_ord_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
/-- All capability dispatch sets reference valid operations in the effect signature. -/
theorem system_conformance :
    (∀ op, op ∈ lean_ord_dispatch → op ∈ allOps) := by
  -- lean_ord dispatch is valid
  have h1 := lean_ord_dispatch_valid
  exact ⟨h1⟩
