namespace LeanStatechartRefExhaustive

-- Ref-extraction exhaustiveness verification
-- Generated by Pneuma

-- Ref-extraction exhaustiveness for api

/-- Ref-kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureApi. -/
def allEffectSignatureApiRefKinds : List EffectSignatureApiRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureApi. -/
theorem EffectSignatureApi_ref_exhaustive :
    ∀ k : EffectSignatureApiRefKind, k ∈ allEffectSignatureApiRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiRefKinds]


-- Ref-extraction exhaustiveness for lean-sc

/-- Ref-kinds for CapabilitySetLeanSc formalism. -/
inductive CapabilitySetLeanScRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetLeanSc. -/
def allCapabilitySetLeanScRefKinds : List CapabilitySetLeanScRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetLeanSc. -/
theorem CapabilitySetLeanSc_ref_exhaustive :
    ∀ k : CapabilitySetLeanScRefKind, k ∈ allCapabilitySetLeanScRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetLeanScRefKinds]


-- Ref-extraction exhaustiveness for type-schema

/-- Ref-kinds for TypeSchema formalism. -/
inductive TypeSchemaRefKind where
  | type_ids
  deriving DecidableEq, Repr

/-- All ref-kinds for TypeSchema. -/
def allTypeSchemaRefKinds : List TypeSchemaRefKind :=
  [.type_ids]

/-- extract-refs handles every ref-kind for TypeSchema. -/
theorem TypeSchema_ref_exhaustive :
    ∀ k : TypeSchemaRefKind, k ∈ allTypeSchemaRefKinds := by
  intro k
  cases k <;> simp [allTypeSchemaRefKinds]

end LeanStatechartRefExhaustive
