namespace MealyRefExhaustive

-- Ref-extraction exhaustiveness verification
-- Generated by Pneuma

-- Ref-extraction exhaustiveness for api

/-- Ref-kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureApi. -/
def allEffectSignatureApiRefKinds : List EffectSignatureApiRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureApi. -/
theorem EffectSignatureApi_ref_exhaustive :
    ∀ k : EffectSignatureApiRefKind, k ∈ allEffectSignatureApiRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiRefKinds]


-- Ref-extraction exhaustiveness for mealy-api

/-- Ref-kinds for CapabilitySetMealyApi formalism. -/
inductive CapabilitySetMealyApiRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetMealyApi. -/
def allCapabilitySetMealyApiRefKinds : List CapabilitySetMealyApiRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetMealyApi. -/
theorem CapabilitySetMealyApi_ref_exhaustive :
    ∀ k : CapabilitySetMealyApiRefKind, k ∈ allCapabilitySetMealyApiRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetMealyApiRefKinds]


-- Ref-extraction exhaustiveness for mealy-ref-kinds

/-- Ref-kinds for CapabilitySetMealyRefKinds formalism. -/
inductive CapabilitySetMealyRefKindsRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetMealyRefKinds. -/
def allCapabilitySetMealyRefKindsRefKinds : List CapabilitySetMealyRefKindsRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetMealyRefKinds. -/
theorem CapabilitySetMealyRefKinds_ref_exhaustive :
    ∀ k : CapabilitySetMealyRefKindsRefKind, k ∈ allCapabilitySetMealyRefKindsRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetMealyRefKindsRefKinds]


-- Ref-extraction exhaustiveness for refs

/-- Ref-kinds for EffectSignatureRefs formalism. -/
inductive EffectSignatureRefsRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureRefs. -/
def allEffectSignatureRefsRefKinds : List EffectSignatureRefsRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureRefs. -/
theorem EffectSignatureRefs_ref_exhaustive :
    ∀ k : EffectSignatureRefsRefKind, k ∈ allEffectSignatureRefsRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureRefsRefKinds]


-- Ref-extraction exhaustiveness for type-schema

/-- Ref-kinds for TypeSchema formalism. -/
inductive TypeSchemaRefKind where
  | type_ids
  deriving DecidableEq, Repr

/-- All ref-kinds for TypeSchema. -/
def allTypeSchemaRefKinds : List TypeSchemaRefKind :=
  [.type_ids]

/-- extract-refs handles every ref-kind for TypeSchema. -/
theorem TypeSchema_ref_exhaustive :
    ∀ k : TypeSchemaRefKind, k ∈ allTypeSchemaRefKinds := by
  intro k
  cases k <;> simp [allTypeSchemaRefKinds]

end MealyRefExhaustive
