-- Generated by Pneuma system-level ->lean projection
-- Source: Mealy
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque DeclarationVec : Type := Unit
opaque KeywordSet : Type := Unit
opaque MealyHandlerSet : Type := Unit
opaque PathSet : Type := Unit

inductive Op where
  | callback_refs
  | emission_op_refs
  | guard_state_refs
  | handler_ids
  | mealy_handler_set
  | update_path_refs
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.callback_refs, .emission_op_refs, .guard_state_refs, .handler_ids, .mealy_handler_set, .update_path_refs]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 6 := by
  rfl

def mealy_api_dispatch : List Op :=
  [.mealy_handler_set]

def mealy_ref_kinds_dispatch : List Op :=
  [.callback_refs, .emission_op_refs, .guard_state_refs, .handler_ids, .update_path_refs]

-- Morphism api-caps->api-ops: mealy_api dispatch ⊆ allOps [conforms]
theorem mealy_api_dispatch_valid :
    ∀ op : Op, op ∈ mealy_api_dispatch → op ∈ allOps := by
  decide

-- Morphism ref-kind-caps->ref-ops: mealy_ref_kinds dispatch ⊆ allOps [conforms]
theorem mealy_ref_kinds_dispatch_valid :
    ∀ op : Op, op ∈ mealy_ref_kinds_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ mealy_api_dispatch → op ∈ allOps) ∧
    (∀ op, op ∈ mealy_ref_kinds_dispatch → op ∈ allOps) := by
  exact ⟨mealy_api_dispatch_valid, mealy_ref_kinds_dispatch_valid⟩
