-- Generated by Pneuma system-level ->lean projection
-- Source: Mealy
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

/-- Opaque proxy for domain type :DeclarationVec. -/
opaque DeclarationVec : Type := Unit
/-- Opaque proxy for domain type :KeywordSet. -/
opaque KeywordSet : Type := Unit
/-- Opaque proxy for domain type :MealyHandlerSet. -/
opaque MealyHandlerSet : Type := Unit
/-- Opaque proxy for domain type :PathSet. -/
opaque PathSet : Type := Unit

/-- Operation alphabet for system specification Mealy. -/
inductive Op where
  | callback_refs
  | emission_op_refs
  | guard_state_refs
  | handler_ids
  | mealy_handler_set
  | update_path_refs
  deriving DecidableEq, Repr

/-- Exhaustive list of all operations in the system specification. -/
def allOps : List Op :=
  [.callback_refs, .emission_op_refs, .guard_state_refs, .handler_ids, .mealy_handler_set, .update_path_refs]

/-- Every member of Op appears in allOps. Proved by case analysis. -/
theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

/-- allOps contains exactly 6 members. -/
theorem allOps_count :
    allOps.length = 6 := by
  rfl

/-- Dispatch operations permitted by capability set :mealy-api. -/
def mealy_api_dispatch : List Op :=
  [.mealy_handler_set]

/-- Dispatch operations permitted by capability set :mealy-ref-kinds. -/
def mealy_ref_kinds_dispatch : List Op :=
  [.callback_refs, .emission_op_refs, .guard_state_refs, .handler_ids, .update_path_refs]

-- Morphism api-caps->api-ops: mealy_api dispatch ⊆ allOps [conforms]
/-- All dispatch operations of :mealy-api are valid members of Op. -/
theorem mealy_api_dispatch_valid :
    ∀ op : Op, op ∈ mealy_api_dispatch → op ∈ allOps := by
  decide

-- Morphism ref-kind-caps->ref-ops: mealy_ref_kinds dispatch ⊆ allOps [conforms]
/-- All dispatch operations of :mealy-ref-kinds are valid members of Op. -/
theorem mealy_ref_kinds_dispatch_valid :
    ∀ op : Op, op ∈ mealy_ref_kinds_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
/-- All capability dispatch sets reference valid operations in the effect signature. -/
theorem system_conformance :
    (∀ op, op ∈ mealy_api_dispatch → op ∈ allOps) ∧
    (∀ op, op ∈ mealy_ref_kinds_dispatch → op ∈ allOps) := by
  -- mealy_api dispatch is valid
  have h1 := mealy_api_dispatch_valid
  -- mealy_ref_kinds dispatch is valid
  have h2 := mealy_ref_kinds_dispatch_valid
  exact ⟨h1, h2⟩
