namespace MealyMonitorSchema

-- Monitor-schema consistency verification
-- Generated by Pneuma

-- Monitor-schema consistency for api

/-- Gap kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureApi. -/
def allEffectSignatureApiGapKinds : List EffectSignatureApiGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_gap_kinds_complete :
    ∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiGapKinds]

/-- Gap statuses for EffectSignatureApi formalism. -/
inductive EffectSignatureApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureApi. -/
def allEffectSignatureApiStatuses : List EffectSignatureApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_statuses_complete :
    ∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureApiStatuses]

/-- Monitor-schema consistency for EffectSignatureApi: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureApi_monitor_schema_consistent :
    (∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds) ∧
    (∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses) := by
  exact ⟨EffectSignatureApi_gap_kinds_complete, EffectSignatureApi_statuses_complete⟩


-- Monitor-schema consistency for mealy-api

/-- Gap kinds for CapabilitySetMealyApi formalism. -/
inductive CapabilitySetMealyApiGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetMealyApi. -/
def allCapabilitySetMealyApiGapKinds : List CapabilitySetMealyApiGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetMealyApi is accounted for. -/
theorem CapabilitySetMealyApi_gap_kinds_complete :
    ∀ k : CapabilitySetMealyApiGapKind, k ∈ allCapabilitySetMealyApiGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetMealyApiGapKinds]

/-- Gap statuses for CapabilitySetMealyApi formalism. -/
inductive CapabilitySetMealyApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetMealyApi. -/
def allCapabilitySetMealyApiStatuses : List CapabilitySetMealyApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetMealyApi is accounted for. -/
theorem CapabilitySetMealyApi_statuses_complete :
    ∀ s : CapabilitySetMealyApiStatus, s ∈ allCapabilitySetMealyApiStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetMealyApiStatuses]

/-- Monitor-schema consistency for CapabilitySetMealyApi: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetMealyApi_monitor_schema_consistent :
    (∀ k : CapabilitySetMealyApiGapKind, k ∈ allCapabilitySetMealyApiGapKinds) ∧
    (∀ s : CapabilitySetMealyApiStatus, s ∈ allCapabilitySetMealyApiStatuses) := by
  exact ⟨CapabilitySetMealyApi_gap_kinds_complete, CapabilitySetMealyApi_statuses_complete⟩


-- Monitor-schema consistency for mealy-ref-kinds

/-- Gap kinds for CapabilitySetMealyRefKinds formalism. -/
inductive CapabilitySetMealyRefKindsGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetMealyRefKinds. -/
def allCapabilitySetMealyRefKindsGapKinds : List CapabilitySetMealyRefKindsGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetMealyRefKinds is accounted for. -/
theorem CapabilitySetMealyRefKinds_gap_kinds_complete :
    ∀ k : CapabilitySetMealyRefKindsGapKind, k ∈ allCapabilitySetMealyRefKindsGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetMealyRefKindsGapKinds]

/-- Gap statuses for CapabilitySetMealyRefKinds formalism. -/
inductive CapabilitySetMealyRefKindsStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetMealyRefKinds. -/
def allCapabilitySetMealyRefKindsStatuses : List CapabilitySetMealyRefKindsStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetMealyRefKinds is accounted for. -/
theorem CapabilitySetMealyRefKinds_statuses_complete :
    ∀ s : CapabilitySetMealyRefKindsStatus, s ∈ allCapabilitySetMealyRefKindsStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetMealyRefKindsStatuses]

/-- Monitor-schema consistency for CapabilitySetMealyRefKinds: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetMealyRefKinds_monitor_schema_consistent :
    (∀ k : CapabilitySetMealyRefKindsGapKind, k ∈ allCapabilitySetMealyRefKindsGapKinds) ∧
    (∀ s : CapabilitySetMealyRefKindsStatus, s ∈ allCapabilitySetMealyRefKindsStatuses) := by
  exact ⟨CapabilitySetMealyRefKinds_gap_kinds_complete, CapabilitySetMealyRefKinds_statuses_complete⟩


-- Monitor-schema consistency for refs

/-- Gap kinds for EffectSignatureRefs formalism. -/
inductive EffectSignatureRefsGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureRefs. -/
def allEffectSignatureRefsGapKinds : List EffectSignatureRefsGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureRefs is accounted for. -/
theorem EffectSignatureRefs_gap_kinds_complete :
    ∀ k : EffectSignatureRefsGapKind, k ∈ allEffectSignatureRefsGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureRefsGapKinds]

/-- Gap statuses for EffectSignatureRefs formalism. -/
inductive EffectSignatureRefsStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureRefs. -/
def allEffectSignatureRefsStatuses : List EffectSignatureRefsStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureRefs is accounted for. -/
theorem EffectSignatureRefs_statuses_complete :
    ∀ s : EffectSignatureRefsStatus, s ∈ allEffectSignatureRefsStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureRefsStatuses]

/-- Monitor-schema consistency for EffectSignatureRefs: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureRefs_monitor_schema_consistent :
    (∀ k : EffectSignatureRefsGapKind, k ∈ allEffectSignatureRefsGapKinds) ∧
    (∀ s : EffectSignatureRefsStatus, s ∈ allEffectSignatureRefsStatuses) := by
  exact ⟨EffectSignatureRefs_gap_kinds_complete, EffectSignatureRefs_statuses_complete⟩


-- Monitor-schema consistency for type-schema

/-- Gap kinds for TypeSchema formalism. -/
inductive TypeSchemaGapKind where
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for TypeSchema. -/
def allTypeSchemaGapKinds : List TypeSchemaGapKind :=
  [.unknown_type]

/-- Every gap kind for TypeSchema is accounted for. -/
theorem TypeSchema_gap_kinds_complete :
    ∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds := by
  intro k
  cases k <;> simp [allTypeSchemaGapKinds]

/-- Gap statuses for TypeSchema formalism. -/
inductive TypeSchemaStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for TypeSchema. -/
def allTypeSchemaStatuses : List TypeSchemaStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for TypeSchema is accounted for. -/
theorem TypeSchema_statuses_complete :
    ∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses := by
  intro s
  cases s <;> simp [allTypeSchemaStatuses]

/-- Monitor-schema consistency for TypeSchema: both gap-kind and status enumerations are exhaustive. -/
theorem TypeSchema_monitor_schema_consistent :
    (∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds) ∧
    (∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses) := by
  exact ⟨TypeSchema_gap_kinds_complete, TypeSchema_statuses_complete⟩

end MealyMonitorSchema
