-- Generated by Pneuma system-level ->lean projection
-- Source: Optic
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque DeclarationVec : Type := Unit
opaque KeywordSet : Type := Unit
opaque OpticDeclaration : Type := Unit
opaque PathSet : Type := Unit

inductive Op where
  | optic_declaration
  | optic_ids
  | paths
  | source_optic_refs
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.optic_declaration, .optic_ids, .paths, .source_optic_refs]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 4 := by
  rfl

def optic_api_dispatch : List Op :=
  [.optic_declaration]

def optic_ref_kinds_dispatch : List Op :=
  [.optic_ids, .paths, .source_optic_refs]

-- Morphism api-caps->api-ops: optic_api dispatch ⊆ allOps [conforms]
theorem optic_api_dispatch_valid :
    ∀ op : Op, op ∈ optic_api_dispatch → op ∈ allOps := by
  decide

-- Morphism ref-kind-caps->ref-ops: optic_ref_kinds dispatch ⊆ allOps [conforms]
theorem optic_ref_kinds_dispatch_valid :
    ∀ op : Op, op ∈ optic_ref_kinds_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ optic_api_dispatch → op ∈ allOps) ∧
    (∀ op, op ∈ optic_ref_kinds_dispatch → op ∈ allOps) := by
  exact ⟨optic_api_dispatch_valid, optic_ref_kinds_dispatch_valid⟩
