namespace OpticMonitorSchema

-- Monitor-schema consistency verification
-- Generated by Pneuma

-- Monitor-schema consistency for api

/-- Gap kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureApi. -/
def allEffectSignatureApiGapKinds : List EffectSignatureApiGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_gap_kinds_complete :
    ∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiGapKinds]

/-- Gap statuses for EffectSignatureApi formalism. -/
inductive EffectSignatureApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureApi. -/
def allEffectSignatureApiStatuses : List EffectSignatureApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_statuses_complete :
    ∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureApiStatuses]

/-- Monitor-schema consistency for EffectSignatureApi: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureApi_monitor_schema_consistent :
    (∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds) ∧
    (∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses) := by
  exact ⟨EffectSignatureApi_gap_kinds_complete, EffectSignatureApi_statuses_complete⟩


-- Monitor-schema consistency for optic-api

/-- Gap kinds for CapabilitySetOpticApi formalism. -/
inductive CapabilitySetOpticApiGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetOpticApi. -/
def allCapabilitySetOpticApiGapKinds : List CapabilitySetOpticApiGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetOpticApi is accounted for. -/
theorem CapabilitySetOpticApi_gap_kinds_complete :
    ∀ k : CapabilitySetOpticApiGapKind, k ∈ allCapabilitySetOpticApiGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetOpticApiGapKinds]

/-- Gap statuses for CapabilitySetOpticApi formalism. -/
inductive CapabilitySetOpticApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetOpticApi. -/
def allCapabilitySetOpticApiStatuses : List CapabilitySetOpticApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetOpticApi is accounted for. -/
theorem CapabilitySetOpticApi_statuses_complete :
    ∀ s : CapabilitySetOpticApiStatus, s ∈ allCapabilitySetOpticApiStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetOpticApiStatuses]

/-- Monitor-schema consistency for CapabilitySetOpticApi: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetOpticApi_monitor_schema_consistent :
    (∀ k : CapabilitySetOpticApiGapKind, k ∈ allCapabilitySetOpticApiGapKinds) ∧
    (∀ s : CapabilitySetOpticApiStatus, s ∈ allCapabilitySetOpticApiStatuses) := by
  exact ⟨CapabilitySetOpticApi_gap_kinds_complete, CapabilitySetOpticApi_statuses_complete⟩


-- Monitor-schema consistency for optic-ref-kinds

/-- Gap kinds for CapabilitySetOpticRefKinds formalism. -/
inductive CapabilitySetOpticRefKindsGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetOpticRefKinds. -/
def allCapabilitySetOpticRefKindsGapKinds : List CapabilitySetOpticRefKindsGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetOpticRefKinds is accounted for. -/
theorem CapabilitySetOpticRefKinds_gap_kinds_complete :
    ∀ k : CapabilitySetOpticRefKindsGapKind, k ∈ allCapabilitySetOpticRefKindsGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetOpticRefKindsGapKinds]

/-- Gap statuses for CapabilitySetOpticRefKinds formalism. -/
inductive CapabilitySetOpticRefKindsStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetOpticRefKinds. -/
def allCapabilitySetOpticRefKindsStatuses : List CapabilitySetOpticRefKindsStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetOpticRefKinds is accounted for. -/
theorem CapabilitySetOpticRefKinds_statuses_complete :
    ∀ s : CapabilitySetOpticRefKindsStatus, s ∈ allCapabilitySetOpticRefKindsStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetOpticRefKindsStatuses]

/-- Monitor-schema consistency for CapabilitySetOpticRefKinds: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetOpticRefKinds_monitor_schema_consistent :
    (∀ k : CapabilitySetOpticRefKindsGapKind, k ∈ allCapabilitySetOpticRefKindsGapKinds) ∧
    (∀ s : CapabilitySetOpticRefKindsStatus, s ∈ allCapabilitySetOpticRefKindsStatuses) := by
  exact ⟨CapabilitySetOpticRefKinds_gap_kinds_complete, CapabilitySetOpticRefKinds_statuses_complete⟩


-- Monitor-schema consistency for refs

/-- Gap kinds for EffectSignatureRefs formalism. -/
inductive EffectSignatureRefsGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureRefs. -/
def allEffectSignatureRefsGapKinds : List EffectSignatureRefsGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureRefs is accounted for. -/
theorem EffectSignatureRefs_gap_kinds_complete :
    ∀ k : EffectSignatureRefsGapKind, k ∈ allEffectSignatureRefsGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureRefsGapKinds]

/-- Gap statuses for EffectSignatureRefs formalism. -/
inductive EffectSignatureRefsStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureRefs. -/
def allEffectSignatureRefsStatuses : List EffectSignatureRefsStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureRefs is accounted for. -/
theorem EffectSignatureRefs_statuses_complete :
    ∀ s : EffectSignatureRefsStatus, s ∈ allEffectSignatureRefsStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureRefsStatuses]

/-- Monitor-schema consistency for EffectSignatureRefs: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureRefs_monitor_schema_consistent :
    (∀ k : EffectSignatureRefsGapKind, k ∈ allEffectSignatureRefsGapKinds) ∧
    (∀ s : EffectSignatureRefsStatus, s ∈ allEffectSignatureRefsStatuses) := by
  exact ⟨EffectSignatureRefs_gap_kinds_complete, EffectSignatureRefs_statuses_complete⟩


-- Monitor-schema consistency for type-schema

/-- Gap kinds for TypeSchema formalism. -/
inductive TypeSchemaGapKind where
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for TypeSchema. -/
def allTypeSchemaGapKinds : List TypeSchemaGapKind :=
  [.unknown_type]

/-- Every gap kind for TypeSchema is accounted for. -/
theorem TypeSchema_gap_kinds_complete :
    ∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds := by
  intro k
  cases k <;> simp [allTypeSchemaGapKinds]

/-- Gap statuses for TypeSchema formalism. -/
inductive TypeSchemaStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for TypeSchema. -/
def allTypeSchemaStatuses : List TypeSchemaStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for TypeSchema is accounted for. -/
theorem TypeSchema_statuses_complete :
    ∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses := by
  intro s
  cases s <;> simp [allTypeSchemaStatuses]

/-- Monitor-schema consistency for TypeSchema: both gap-kind and status enumerations are exhaustive. -/
theorem TypeSchema_monitor_schema_consistent :
    (∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds) ∧
    (∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses) := by
  exact ⟨TypeSchema_gap_kinds_complete, TypeSchema_statuses_complete⟩

end OpticMonitorSchema
