namespace OpticRefExhaustive

-- Ref-extraction exhaustiveness verification
-- Generated by Pneuma

-- Ref-extraction exhaustiveness for api

/-- Ref-kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureApi. -/
def allEffectSignatureApiRefKinds : List EffectSignatureApiRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureApi. -/
theorem EffectSignatureApi_ref_exhaustive :
    ∀ k : EffectSignatureApiRefKind, k ∈ allEffectSignatureApiRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiRefKinds]


-- Ref-extraction exhaustiveness for optic-api

/-- Ref-kinds for CapabilitySetOpticApi formalism. -/
inductive CapabilitySetOpticApiRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetOpticApi. -/
def allCapabilitySetOpticApiRefKinds : List CapabilitySetOpticApiRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetOpticApi. -/
theorem CapabilitySetOpticApi_ref_exhaustive :
    ∀ k : CapabilitySetOpticApiRefKind, k ∈ allCapabilitySetOpticApiRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetOpticApiRefKinds]


-- Ref-extraction exhaustiveness for optic-ref-kinds

/-- Ref-kinds for CapabilitySetOpticRefKinds formalism. -/
inductive CapabilitySetOpticRefKindsRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetOpticRefKinds. -/
def allCapabilitySetOpticRefKindsRefKinds : List CapabilitySetOpticRefKindsRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetOpticRefKinds. -/
theorem CapabilitySetOpticRefKinds_ref_exhaustive :
    ∀ k : CapabilitySetOpticRefKindsRefKind, k ∈ allCapabilitySetOpticRefKindsRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetOpticRefKindsRefKinds]


-- Ref-extraction exhaustiveness for refs

/-- Ref-kinds for EffectSignatureRefs formalism. -/
inductive EffectSignatureRefsRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureRefs. -/
def allEffectSignatureRefsRefKinds : List EffectSignatureRefsRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureRefs. -/
theorem EffectSignatureRefs_ref_exhaustive :
    ∀ k : EffectSignatureRefsRefKind, k ∈ allEffectSignatureRefsRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureRefsRefKinds]


-- Ref-extraction exhaustiveness for type-schema

/-- Ref-kinds for TypeSchema formalism. -/
inductive TypeSchemaRefKind where
  | type_ids
  deriving DecidableEq, Repr

/-- All ref-kinds for TypeSchema. -/
def allTypeSchemaRefKinds : List TypeSchemaRefKind :=
  [.type_ids]

/-- extract-refs handles every ref-kind for TypeSchema. -/
theorem TypeSchema_ref_exhaustive :
    ∀ k : TypeSchemaRefKind, k ∈ allTypeSchemaRefKinds := by
  intro k
  cases k <;> simp [allTypeSchemaRefKinds]

end OpticRefExhaustive
