namespace OrderingRefExhaustive

-- Ref-extraction exhaustiveness verification
-- Generated by Pneuma

-- Ref-extraction exhaustiveness for api

/-- Ref-kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureApi. -/
def allEffectSignatureApiRefKinds : List EffectSignatureApiRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureApi. -/
theorem EffectSignatureApi_ref_exhaustive :
    ∀ k : EffectSignatureApiRefKind, k ∈ allEffectSignatureApiRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiRefKinds]


-- Ref-extraction exhaustiveness for check

/-- Ref-kinds for EffectSignatureCheck formalism. -/
inductive EffectSignatureCheckRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureCheck. -/
def allEffectSignatureCheckRefKinds : List EffectSignatureCheckRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureCheck. -/
theorem EffectSignatureCheck_ref_exhaustive :
    ∀ k : EffectSignatureCheckRefKind, k ∈ allEffectSignatureCheckRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureCheckRefKinds]


-- Ref-extraction exhaustiveness for ord-api

/-- Ref-kinds for CapabilitySetOrdApi formalism. -/
inductive CapabilitySetOrdApiRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetOrdApi. -/
def allCapabilitySetOrdApiRefKinds : List CapabilitySetOrdApiRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetOrdApi. -/
theorem CapabilitySetOrdApi_ref_exhaustive :
    ∀ k : CapabilitySetOrdApiRefKind, k ∈ allCapabilitySetOrdApiRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetOrdApiRefKinds]


-- Ref-extraction exhaustiveness for ord-check

/-- Ref-kinds for CapabilitySetOrdCheck formalism. -/
inductive CapabilitySetOrdCheckRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetOrdCheck. -/
def allCapabilitySetOrdCheckRefKinds : List CapabilitySetOrdCheckRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetOrdCheck. -/
theorem CapabilitySetOrdCheck_ref_exhaustive :
    ∀ k : CapabilitySetOrdCheckRefKind, k ∈ allCapabilitySetOrdCheckRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetOrdCheckRefKinds]


-- Ref-extraction exhaustiveness for type-schema

/-- Ref-kinds for TypeSchema formalism. -/
inductive TypeSchemaRefKind where
  | type_ids
  deriving DecidableEq, Repr

/-- All ref-kinds for TypeSchema. -/
def allTypeSchemaRefKinds : List TypeSchemaRefKind :=
  [.type_ids]

/-- extract-refs handles every ref-kind for TypeSchema. -/
theorem TypeSchema_ref_exhaustive :
    ∀ k : TypeSchemaRefKind, k ∈ allTypeSchemaRefKinds := by
  intro k
  cases k <;> simp [allTypeSchemaRefKinds]

end OrderingRefExhaustive
