namespace OrderingMonitorSchema

-- Monitor-schema consistency verification
-- Generated by Pneuma

-- Monitor-schema consistency for api

/-- Gap kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureApi. -/
def allEffectSignatureApiGapKinds : List EffectSignatureApiGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_gap_kinds_complete :
    ∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiGapKinds]

/-- Gap statuses for EffectSignatureApi formalism. -/
inductive EffectSignatureApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureApi. -/
def allEffectSignatureApiStatuses : List EffectSignatureApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_statuses_complete :
    ∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureApiStatuses]

/-- Monitor-schema consistency for EffectSignatureApi: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureApi_monitor_schema_consistent :
    (∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds) ∧
    (∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses) := by
  exact ⟨EffectSignatureApi_gap_kinds_complete, EffectSignatureApi_statuses_complete⟩


-- Monitor-schema consistency for check

/-- Gap kinds for EffectSignatureCheck formalism. -/
inductive EffectSignatureCheckGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureCheck. -/
def allEffectSignatureCheckGapKinds : List EffectSignatureCheckGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureCheck is accounted for. -/
theorem EffectSignatureCheck_gap_kinds_complete :
    ∀ k : EffectSignatureCheckGapKind, k ∈ allEffectSignatureCheckGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureCheckGapKinds]

/-- Gap statuses for EffectSignatureCheck formalism. -/
inductive EffectSignatureCheckStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureCheck. -/
def allEffectSignatureCheckStatuses : List EffectSignatureCheckStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureCheck is accounted for. -/
theorem EffectSignatureCheck_statuses_complete :
    ∀ s : EffectSignatureCheckStatus, s ∈ allEffectSignatureCheckStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureCheckStatuses]

/-- Monitor-schema consistency for EffectSignatureCheck: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureCheck_monitor_schema_consistent :
    (∀ k : EffectSignatureCheckGapKind, k ∈ allEffectSignatureCheckGapKinds) ∧
    (∀ s : EffectSignatureCheckStatus, s ∈ allEffectSignatureCheckStatuses) := by
  exact ⟨EffectSignatureCheck_gap_kinds_complete, EffectSignatureCheck_statuses_complete⟩


-- Monitor-schema consistency for ord-api

/-- Gap kinds for CapabilitySetOrdApi formalism. -/
inductive CapabilitySetOrdApiGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetOrdApi. -/
def allCapabilitySetOrdApiGapKinds : List CapabilitySetOrdApiGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetOrdApi is accounted for. -/
theorem CapabilitySetOrdApi_gap_kinds_complete :
    ∀ k : CapabilitySetOrdApiGapKind, k ∈ allCapabilitySetOrdApiGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetOrdApiGapKinds]

/-- Gap statuses for CapabilitySetOrdApi formalism. -/
inductive CapabilitySetOrdApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetOrdApi. -/
def allCapabilitySetOrdApiStatuses : List CapabilitySetOrdApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetOrdApi is accounted for. -/
theorem CapabilitySetOrdApi_statuses_complete :
    ∀ s : CapabilitySetOrdApiStatus, s ∈ allCapabilitySetOrdApiStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetOrdApiStatuses]

/-- Monitor-schema consistency for CapabilitySetOrdApi: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetOrdApi_monitor_schema_consistent :
    (∀ k : CapabilitySetOrdApiGapKind, k ∈ allCapabilitySetOrdApiGapKinds) ∧
    (∀ s : CapabilitySetOrdApiStatus, s ∈ allCapabilitySetOrdApiStatuses) := by
  exact ⟨CapabilitySetOrdApi_gap_kinds_complete, CapabilitySetOrdApi_statuses_complete⟩


-- Monitor-schema consistency for ord-check

/-- Gap kinds for CapabilitySetOrdCheck formalism. -/
inductive CapabilitySetOrdCheckGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetOrdCheck. -/
def allCapabilitySetOrdCheckGapKinds : List CapabilitySetOrdCheckGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetOrdCheck is accounted for. -/
theorem CapabilitySetOrdCheck_gap_kinds_complete :
    ∀ k : CapabilitySetOrdCheckGapKind, k ∈ allCapabilitySetOrdCheckGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetOrdCheckGapKinds]

/-- Gap statuses for CapabilitySetOrdCheck formalism. -/
inductive CapabilitySetOrdCheckStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetOrdCheck. -/
def allCapabilitySetOrdCheckStatuses : List CapabilitySetOrdCheckStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetOrdCheck is accounted for. -/
theorem CapabilitySetOrdCheck_statuses_complete :
    ∀ s : CapabilitySetOrdCheckStatus, s ∈ allCapabilitySetOrdCheckStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetOrdCheckStatuses]

/-- Monitor-schema consistency for CapabilitySetOrdCheck: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetOrdCheck_monitor_schema_consistent :
    (∀ k : CapabilitySetOrdCheckGapKind, k ∈ allCapabilitySetOrdCheckGapKinds) ∧
    (∀ s : CapabilitySetOrdCheckStatus, s ∈ allCapabilitySetOrdCheckStatuses) := by
  exact ⟨CapabilitySetOrdCheck_gap_kinds_complete, CapabilitySetOrdCheck_statuses_complete⟩


-- Monitor-schema consistency for type-schema

/-- Gap kinds for TypeSchema formalism. -/
inductive TypeSchemaGapKind where
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for TypeSchema. -/
def allTypeSchemaGapKinds : List TypeSchemaGapKind :=
  [.unknown_type]

/-- Every gap kind for TypeSchema is accounted for. -/
theorem TypeSchema_gap_kinds_complete :
    ∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds := by
  intro k
  cases k <;> simp [allTypeSchemaGapKinds]

/-- Gap statuses for TypeSchema formalism. -/
inductive TypeSchemaStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for TypeSchema. -/
def allTypeSchemaStatuses : List TypeSchemaStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for TypeSchema is accounted for. -/
theorem TypeSchema_statuses_complete :
    ∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses := by
  intro s
  cases s <;> simp [allTypeSchemaStatuses]

/-- Monitor-schema consistency for TypeSchema: both gap-kind and status enumerations are exhaustive. -/
theorem TypeSchema_monitor_schema_consistent :
    (∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds) ∧
    (∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses) := by
  exact ⟨TypeSchema_gap_kinds_complete, TypeSchema_statuses_complete⟩

end OrderingMonitorSchema
