-- Generated by Pneuma system-level ->lean projection
-- Source: Ordering
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque GapSeq : Type := Unit
opaque IReferenceable : Type := Unit
opaque Keyword : Type := Unit
opaque OrderedSeq : Type := Unit
opaque OrderingMorphism : Type := Unit
opaque RefinementMap : Type := Unit

inductive Op where
  | check
  | ordering_morphism
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.check, .ordering_morphism]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 2 := by
  rfl

def ord_api_dispatch : List Op :=
  [.ordering_morphism]

def ord_check_dispatch : List Op :=
  [.check]

-- Morphism api-caps->api-ops: ord_api dispatch ⊆ allOps [conforms]
theorem ord_api_dispatch_valid :
    ∀ op : Op, op ∈ ord_api_dispatch → op ∈ allOps := by
  decide

-- Morphism check-caps->check-ops: ord_check dispatch ⊆ allOps [conforms]
theorem ord_check_dispatch_valid :
    ∀ op : Op, op ∈ ord_check_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ ord_api_dispatch → op ∈ allOps) ∧
    (∀ op, op ∈ ord_check_dispatch → op ∈ allOps) := by
  exact ⟨ord_api_dispatch_valid, ord_check_dispatch_valid⟩
