namespace PathGraphMonitorSchema

-- Monitor-schema consistency verification
-- Generated by Pneuma

-- Monitor-schema consistency for api

/-- Gap kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureApi. -/
def allEffectSignatureApiGapKinds : List EffectSignatureApiGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_gap_kinds_complete :
    ∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiGapKinds]

/-- Gap statuses for EffectSignatureApi formalism. -/
inductive EffectSignatureApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureApi. -/
def allEffectSignatureApiStatuses : List EffectSignatureApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_statuses_complete :
    ∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureApiStatuses]

/-- Monitor-schema consistency for EffectSignatureApi: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureApi_monitor_schema_consistent :
    (∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds) ∧
    (∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses) := by
  exact ⟨EffectSignatureApi_gap_kinds_complete, EffectSignatureApi_statuses_complete⟩


-- Monitor-schema consistency for graph-api

/-- Gap kinds for CapabilitySetGraphApi formalism. -/
inductive CapabilitySetGraphApiGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetGraphApi. -/
def allCapabilitySetGraphApiGapKinds : List CapabilitySetGraphApiGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetGraphApi is accounted for. -/
theorem CapabilitySetGraphApi_gap_kinds_complete :
    ∀ k : CapabilitySetGraphApiGapKind, k ∈ allCapabilitySetGraphApiGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetGraphApiGapKinds]

/-- Gap statuses for CapabilitySetGraphApi formalism. -/
inductive CapabilitySetGraphApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetGraphApi. -/
def allCapabilitySetGraphApiStatuses : List CapabilitySetGraphApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetGraphApi is accounted for. -/
theorem CapabilitySetGraphApi_statuses_complete :
    ∀ s : CapabilitySetGraphApiStatus, s ∈ allCapabilitySetGraphApiStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetGraphApiStatuses]

/-- Monitor-schema consistency for CapabilitySetGraphApi: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetGraphApi_monitor_schema_consistent :
    (∀ k : CapabilitySetGraphApiGapKind, k ∈ allCapabilitySetGraphApiGapKinds) ∧
    (∀ s : CapabilitySetGraphApiStatus, s ∈ allCapabilitySetGraphApiStatuses) := by
  exact ⟨CapabilitySetGraphApi_gap_kinds_complete, CapabilitySetGraphApi_statuses_complete⟩


-- Monitor-schema consistency for type-schema

/-- Gap kinds for TypeSchema formalism. -/
inductive TypeSchemaGapKind where
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for TypeSchema. -/
def allTypeSchemaGapKinds : List TypeSchemaGapKind :=
  [.unknown_type]

/-- Every gap kind for TypeSchema is accounted for. -/
theorem TypeSchema_gap_kinds_complete :
    ∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds := by
  intro k
  cases k <;> simp [allTypeSchemaGapKinds]

/-- Gap statuses for TypeSchema formalism. -/
inductive TypeSchemaStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for TypeSchema. -/
def allTypeSchemaStatuses : List TypeSchemaStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for TypeSchema is accounted for. -/
theorem TypeSchema_statuses_complete :
    ∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses := by
  intro s
  cases s <;> simp [allTypeSchemaStatuses]

/-- Monitor-schema consistency for TypeSchema: both gap-kind and status enumerations are exhaustive. -/
theorem TypeSchema_monitor_schema_consistent :
    (∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds) ∧
    (∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses) := by
  exact ⟨TypeSchema_gap_kinds_complete, TypeSchema_statuses_complete⟩

end PathGraphMonitorSchema
