-- Generated by Pneuma system-level ->lean projection
-- Source: PathGraph
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque AdjacencyMap : Type := Unit
opaque CircuitVec : Type := Unit
opaque EdgeIndex : Type := Unit
opaque Registry : Type := Unit

inductive Op where
  | elementary_circuits
  | registry_>edge_index
  | registry_>graph
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.elementary_circuits, .registry_>edge_index, .registry_>graph]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 3 := by
  rfl

def graph_api_dispatch : List Op :=
  [.elementary_circuits, .registry_>edge_index, .registry_>graph]

-- Morphism api-caps->api-ops: graph_api dispatch ⊆ allOps [conforms]
theorem graph_api_dispatch_valid :
    ∀ op : Op, op ∈ graph_api_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ graph_api_dispatch → op ∈ allOps) := by
  exact ⟨graph_api_dispatch_valid⟩
