-- Generated by Pneuma system-level ->lean projection
-- Source: PathCore
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque ComposedPath : Type := Unit
opaque ComposedPathVec : Type := Unit
opaque EdgeIndex : Type := Unit
opaque GapMap : Type := Unit
opaque GapVec : Type := Unit
opaque NodeVec : Type := Unit
opaque Registry : Type := Unit

inductive Op where
  | check_adjacency
  | check_all_paths
  | check_closure
  | check_path
  | circuit_>paths
  | find_paths
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.check_adjacency, .check_all_paths, .check_closure, .check_path, .circuit_>paths, .find_paths]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 6 := by
  rfl

def path_api_dispatch : List Op :=
  [.check_adjacency, .check_all_paths, .check_closure, .check_path, .circuit_>paths, .find_paths]

-- Morphism api-caps->api-ops: path_api dispatch ⊆ allOps [conforms]
theorem path_api_dispatch_valid :
    ∀ op : Op, op ∈ path_api_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ path_api_dispatch → op ∈ allOps) := by
  exact ⟨path_api_dispatch_valid⟩
