namespace ProtocolRefExhaustive

-- Ref-extraction exhaustiveness verification
-- Generated by Pneuma

-- Ref-extraction exhaustiveness for effect-signature

/-- Ref-kinds for EffectSignature formalism. -/
inductive EffectSignatureRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignature. -/
def allEffectSignatureRefKinds : List EffectSignatureRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignature. -/
theorem EffectSignature_ref_exhaustive :
    ∀ k : EffectSignatureRefKind, k ∈ allEffectSignatureRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureRefKinds]


-- Ref-extraction exhaustiveness for formalism

/-- Ref-kinds for CapabilitySetFormalism formalism. -/
inductive CapabilitySetFormalismRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetFormalism. -/
def allCapabilitySetFormalismRefKinds : List CapabilitySetFormalismRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetFormalism. -/
theorem CapabilitySetFormalism_ref_exhaustive :
    ∀ k : CapabilitySetFormalismRefKind, k ∈ allCapabilitySetFormalismRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetFormalismRefKinds]


-- Ref-extraction exhaustiveness for morphism

/-- Ref-kinds for CapabilitySetMorphism formalism. -/
inductive CapabilitySetMorphismRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetMorphism. -/
def allCapabilitySetMorphismRefKinds : List CapabilitySetMorphismRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetMorphism. -/
theorem CapabilitySetMorphism_ref_exhaustive :
    ∀ k : CapabilitySetMorphismRefKind, k ∈ allCapabilitySetMorphismRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetMorphismRefKinds]


-- Ref-extraction exhaustiveness for type-schema

/-- Ref-kinds for TypeSchema formalism. -/
inductive TypeSchemaRefKind where
  | type_ids
  deriving DecidableEq, Repr

/-- All ref-kinds for TypeSchema. -/
def allTypeSchemaRefKinds : List TypeSchemaRefKind :=
  [.type_ids]

/-- extract-refs handles every ref-kind for TypeSchema. -/
theorem TypeSchema_ref_exhaustive :
    ∀ k : TypeSchemaRefKind, k ∈ allTypeSchemaRefKinds := by
  intro k
  cases k <;> simp [allTypeSchemaRefKinds]

end ProtocolRefExhaustive
