-- Generated by Pneuma system-level ->lean projection
-- Source: Refinement
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque AccessorMap : Type := Unit
opaque Any : Type := Unit
opaque Keyword : Type := Unit
opaque NsVec : Type := Unit
opaque RefinementMap : Type := Unit
opaque VarRef : Type := Unit

inductive Op where
  | access
  | deref_event_log
  | deref_state
  | refinement_map
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.access, .deref_event_log, .deref_state, .refinement_map]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 4 := by
  rfl

def rm_api_dispatch : List Op :=
  [.access, .deref_event_log, .deref_state, .refinement_map]

-- Morphism api-caps->api-ops: rm_api dispatch ⊆ allOps [conforms]
theorem rm_api_dispatch_valid :
    ∀ op : Op, op ∈ rm_api_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ rm_api_dispatch → op ∈ allOps) := by
  exact ⟨rm_api_dispatch_valid⟩
