-- Generated by Pneuma system-level ->lean projection
-- Source: Registry
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque Keyword : Type := Unit
opaque Registry : Type := Unit

inductive Op where
  | default_registry
  | morphisms_involving
  | morphisms_of_kind
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.default_registry, .morphisms_involving, .morphisms_of_kind]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 3 := by
  rfl

def reg_api_dispatch : List Op :=
  [.default_registry, .morphisms_involving, .morphisms_of_kind]

-- Morphism api-caps->api-ops: reg_api dispatch ⊆ allOps [conforms]
theorem reg_api_dispatch_valid :
    ∀ op : Op, op ∈ reg_api_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ reg_api_dispatch → op ∈ allOps) := by
  exact ⟨reg_api_dispatch_valid⟩
