-- Generated by Pneuma system-level ->lean projection
-- Source: Resolver
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque DeclarationMap : Type := Unit
opaque DeclarationVec : Type := Unit
opaque KeywordSet : Type := Unit
opaque ResolverGraph : Type := Unit

inductive Op where
  | external_sources
  | input_attributes
  | output_attributes
  | reachable_attributes
  | resolver_graph
  | resolver_ids
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.external_sources, .input_attributes, .output_attributes, .reachable_attributes, .resolver_graph, .resolver_ids]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 6 := by
  rfl

def resolver_api_dispatch : List Op :=
  [.reachable_attributes, .resolver_graph]

def resolver_ref_kinds_dispatch : List Op :=
  [.external_sources, .input_attributes, .output_attributes, .resolver_ids]

-- Morphism api-caps->api-ops: resolver_api dispatch ⊆ allOps [conforms]
theorem resolver_api_dispatch_valid :
    ∀ op : Op, op ∈ resolver_api_dispatch → op ∈ allOps := by
  decide

-- Morphism ref-kind-caps->ref-ops: resolver_ref_kinds dispatch ⊆ allOps [conforms]
theorem resolver_ref_kinds_dispatch_valid :
    ∀ op : Op, op ∈ resolver_ref_kinds_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ resolver_api_dispatch → op ∈ allOps) ∧
    (∀ op, op ∈ resolver_ref_kinds_dispatch → op ∈ allOps) := by
  exact ⟨resolver_api_dispatch_valid, resolver_ref_kinds_dispatch_valid⟩
