namespace ResolverMonitorSchema

-- Monitor-schema consistency verification
-- Generated by Pneuma

-- Monitor-schema consistency for api

/-- Gap kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureApi. -/
def allEffectSignatureApiGapKinds : List EffectSignatureApiGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_gap_kinds_complete :
    ∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiGapKinds]

/-- Gap statuses for EffectSignatureApi formalism. -/
inductive EffectSignatureApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureApi. -/
def allEffectSignatureApiStatuses : List EffectSignatureApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_statuses_complete :
    ∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureApiStatuses]

/-- Monitor-schema consistency for EffectSignatureApi: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureApi_monitor_schema_consistent :
    (∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds) ∧
    (∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses) := by
  exact ⟨EffectSignatureApi_gap_kinds_complete, EffectSignatureApi_statuses_complete⟩


-- Monitor-schema consistency for refs

/-- Gap kinds for EffectSignatureRefs formalism. -/
inductive EffectSignatureRefsGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureRefs. -/
def allEffectSignatureRefsGapKinds : List EffectSignatureRefsGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureRefs is accounted for. -/
theorem EffectSignatureRefs_gap_kinds_complete :
    ∀ k : EffectSignatureRefsGapKind, k ∈ allEffectSignatureRefsGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureRefsGapKinds]

/-- Gap statuses for EffectSignatureRefs formalism. -/
inductive EffectSignatureRefsStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureRefs. -/
def allEffectSignatureRefsStatuses : List EffectSignatureRefsStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureRefs is accounted for. -/
theorem EffectSignatureRefs_statuses_complete :
    ∀ s : EffectSignatureRefsStatus, s ∈ allEffectSignatureRefsStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureRefsStatuses]

/-- Monitor-schema consistency for EffectSignatureRefs: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureRefs_monitor_schema_consistent :
    (∀ k : EffectSignatureRefsGapKind, k ∈ allEffectSignatureRefsGapKinds) ∧
    (∀ s : EffectSignatureRefsStatus, s ∈ allEffectSignatureRefsStatuses) := by
  exact ⟨EffectSignatureRefs_gap_kinds_complete, EffectSignatureRefs_statuses_complete⟩


-- Monitor-schema consistency for resolver-api

/-- Gap kinds for CapabilitySetResolverApi formalism. -/
inductive CapabilitySetResolverApiGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetResolverApi. -/
def allCapabilitySetResolverApiGapKinds : List CapabilitySetResolverApiGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetResolverApi is accounted for. -/
theorem CapabilitySetResolverApi_gap_kinds_complete :
    ∀ k : CapabilitySetResolverApiGapKind, k ∈ allCapabilitySetResolverApiGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetResolverApiGapKinds]

/-- Gap statuses for CapabilitySetResolverApi formalism. -/
inductive CapabilitySetResolverApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetResolverApi. -/
def allCapabilitySetResolverApiStatuses : List CapabilitySetResolverApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetResolverApi is accounted for. -/
theorem CapabilitySetResolverApi_statuses_complete :
    ∀ s : CapabilitySetResolverApiStatus, s ∈ allCapabilitySetResolverApiStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetResolverApiStatuses]

/-- Monitor-schema consistency for CapabilitySetResolverApi: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetResolverApi_monitor_schema_consistent :
    (∀ k : CapabilitySetResolverApiGapKind, k ∈ allCapabilitySetResolverApiGapKinds) ∧
    (∀ s : CapabilitySetResolverApiStatus, s ∈ allCapabilitySetResolverApiStatuses) := by
  exact ⟨CapabilitySetResolverApi_gap_kinds_complete, CapabilitySetResolverApi_statuses_complete⟩


-- Monitor-schema consistency for resolver-ref-kinds

/-- Gap kinds for CapabilitySetResolverRefKinds formalism. -/
inductive CapabilitySetResolverRefKindsGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetResolverRefKinds. -/
def allCapabilitySetResolverRefKindsGapKinds : List CapabilitySetResolverRefKindsGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetResolverRefKinds is accounted for. -/
theorem CapabilitySetResolverRefKinds_gap_kinds_complete :
    ∀ k : CapabilitySetResolverRefKindsGapKind, k ∈ allCapabilitySetResolverRefKindsGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetResolverRefKindsGapKinds]

/-- Gap statuses for CapabilitySetResolverRefKinds formalism. -/
inductive CapabilitySetResolverRefKindsStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetResolverRefKinds. -/
def allCapabilitySetResolverRefKindsStatuses : List CapabilitySetResolverRefKindsStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetResolverRefKinds is accounted for. -/
theorem CapabilitySetResolverRefKinds_statuses_complete :
    ∀ s : CapabilitySetResolverRefKindsStatus, s ∈ allCapabilitySetResolverRefKindsStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetResolverRefKindsStatuses]

/-- Monitor-schema consistency for CapabilitySetResolverRefKinds: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetResolverRefKinds_monitor_schema_consistent :
    (∀ k : CapabilitySetResolverRefKindsGapKind, k ∈ allCapabilitySetResolverRefKindsGapKinds) ∧
    (∀ s : CapabilitySetResolverRefKindsStatus, s ∈ allCapabilitySetResolverRefKindsStatuses) := by
  exact ⟨CapabilitySetResolverRefKinds_gap_kinds_complete, CapabilitySetResolverRefKinds_statuses_complete⟩


-- Monitor-schema consistency for type-schema

/-- Gap kinds for TypeSchema formalism. -/
inductive TypeSchemaGapKind where
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for TypeSchema. -/
def allTypeSchemaGapKinds : List TypeSchemaGapKind :=
  [.unknown_type]

/-- Every gap kind for TypeSchema is accounted for. -/
theorem TypeSchema_gap_kinds_complete :
    ∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds := by
  intro k
  cases k <;> simp [allTypeSchemaGapKinds]

/-- Gap statuses for TypeSchema formalism. -/
inductive TypeSchemaStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for TypeSchema. -/
def allTypeSchemaStatuses : List TypeSchemaStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for TypeSchema is accounted for. -/
theorem TypeSchema_statuses_complete :
    ∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses := by
  intro s
  cases s <;> simp [allTypeSchemaStatuses]

/-- Monitor-schema consistency for TypeSchema: both gap-kind and status enumerations are exhaustive. -/
theorem TypeSchema_monitor_schema_consistent :
    (∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds) ∧
    (∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses) := by
  exact ⟨TypeSchema_gap_kinds_complete, TypeSchema_statuses_complete⟩

end ResolverMonitorSchema
