namespace StatechartMonitorSchema

-- Monitor-schema consistency verification
-- Generated by Pneuma

-- Monitor-schema consistency for api

/-- Gap kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureApi. -/
def allEffectSignatureApiGapKinds : List EffectSignatureApiGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_gap_kinds_complete :
    ∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiGapKinds]

/-- Gap statuses for EffectSignatureApi formalism. -/
inductive EffectSignatureApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureApi. -/
def allEffectSignatureApiStatuses : List EffectSignatureApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureApi is accounted for. -/
theorem EffectSignatureApi_statuses_complete :
    ∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureApiStatuses]

/-- Monitor-schema consistency for EffectSignatureApi: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureApi_monitor_schema_consistent :
    (∀ k : EffectSignatureApiGapKind, k ∈ allEffectSignatureApiGapKinds) ∧
    (∀ s : EffectSignatureApiStatus, s ∈ allEffectSignatureApiStatuses) := by
  exact ⟨EffectSignatureApi_gap_kinds_complete, EffectSignatureApi_statuses_complete⟩


-- Monitor-schema consistency for refs

/-- Gap kinds for EffectSignatureRefs formalism. -/
inductive EffectSignatureRefsGapKind where
  | malformed_fields
  | missing_op_key
  | missing_operation
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for EffectSignatureRefs. -/
def allEffectSignatureRefsGapKinds : List EffectSignatureRefsGapKind :=
  [.malformed_fields, .missing_op_key, .missing_operation, .unknown_type]

/-- Every gap kind for EffectSignatureRefs is accounted for. -/
theorem EffectSignatureRefs_gap_kinds_complete :
    ∀ k : EffectSignatureRefsGapKind, k ∈ allEffectSignatureRefsGapKinds := by
  intro k
  cases k <;> simp [allEffectSignatureRefsGapKinds]

/-- Gap statuses for EffectSignatureRefs formalism. -/
inductive EffectSignatureRefsStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for EffectSignatureRefs. -/
def allEffectSignatureRefsStatuses : List EffectSignatureRefsStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for EffectSignatureRefs is accounted for. -/
theorem EffectSignatureRefs_statuses_complete :
    ∀ s : EffectSignatureRefsStatus, s ∈ allEffectSignatureRefsStatuses := by
  intro s
  cases s <;> simp [allEffectSignatureRefsStatuses]

/-- Monitor-schema consistency for EffectSignatureRefs: both gap-kind and status enumerations are exhaustive. -/
theorem EffectSignatureRefs_monitor_schema_consistent :
    (∀ k : EffectSignatureRefsGapKind, k ∈ allEffectSignatureRefsGapKinds) ∧
    (∀ s : EffectSignatureRefsStatus, s ∈ allEffectSignatureRefsStatuses) := by
  exact ⟨EffectSignatureRefs_gap_kinds_complete, EffectSignatureRefs_statuses_complete⟩


-- Monitor-schema consistency for sc-api

/-- Gap kinds for CapabilitySetScApi formalism. -/
inductive CapabilitySetScApiGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetScApi. -/
def allCapabilitySetScApiGapKinds : List CapabilitySetScApiGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetScApi is accounted for. -/
theorem CapabilitySetScApi_gap_kinds_complete :
    ∀ k : CapabilitySetScApiGapKind, k ∈ allCapabilitySetScApiGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetScApiGapKinds]

/-- Gap statuses for CapabilitySetScApi formalism. -/
inductive CapabilitySetScApiStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetScApi. -/
def allCapabilitySetScApiStatuses : List CapabilitySetScApiStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetScApi is accounted for. -/
theorem CapabilitySetScApi_statuses_complete :
    ∀ s : CapabilitySetScApiStatus, s ∈ allCapabilitySetScApiStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetScApiStatuses]

/-- Monitor-schema consistency for CapabilitySetScApi: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetScApi_monitor_schema_consistent :
    (∀ k : CapabilitySetScApiGapKind, k ∈ allCapabilitySetScApiGapKinds) ∧
    (∀ s : CapabilitySetScApiStatus, s ∈ allCapabilitySetScApiStatuses) := by
  exact ⟨CapabilitySetScApi_gap_kinds_complete, CapabilitySetScApi_statuses_complete⟩


-- Monitor-schema consistency for sc-ref-kinds

/-- Gap kinds for CapabilitySetScRefKinds formalism. -/
inductive CapabilitySetScRefKindsGapKind where
  | empty_set
  | unauthorized
  deriving DecidableEq, Repr

/-- All gap kinds for CapabilitySetScRefKinds. -/
def allCapabilitySetScRefKindsGapKinds : List CapabilitySetScRefKindsGapKind :=
  [.empty_set, .unauthorized]

/-- Every gap kind for CapabilitySetScRefKinds is accounted for. -/
theorem CapabilitySetScRefKinds_gap_kinds_complete :
    ∀ k : CapabilitySetScRefKindsGapKind, k ∈ allCapabilitySetScRefKindsGapKinds := by
  intro k
  cases k <;> simp [allCapabilitySetScRefKindsGapKinds]

/-- Gap statuses for CapabilitySetScRefKinds formalism. -/
inductive CapabilitySetScRefKindsStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for CapabilitySetScRefKinds. -/
def allCapabilitySetScRefKindsStatuses : List CapabilitySetScRefKindsStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for CapabilitySetScRefKinds is accounted for. -/
theorem CapabilitySetScRefKinds_statuses_complete :
    ∀ s : CapabilitySetScRefKindsStatus, s ∈ allCapabilitySetScRefKindsStatuses := by
  intro s
  cases s <;> simp [allCapabilitySetScRefKindsStatuses]

/-- Monitor-schema consistency for CapabilitySetScRefKinds: both gap-kind and status enumerations are exhaustive. -/
theorem CapabilitySetScRefKinds_monitor_schema_consistent :
    (∀ k : CapabilitySetScRefKindsGapKind, k ∈ allCapabilitySetScRefKindsGapKinds) ∧
    (∀ s : CapabilitySetScRefKindsStatus, s ∈ allCapabilitySetScRefKindsStatuses) := by
  exact ⟨CapabilitySetScRefKinds_gap_kinds_complete, CapabilitySetScRefKinds_statuses_complete⟩


-- Monitor-schema consistency for type-schema

/-- Gap kinds for TypeSchema formalism. -/
inductive TypeSchemaGapKind where
  | unknown_type
  deriving DecidableEq, Repr

/-- All gap kinds for TypeSchema. -/
def allTypeSchemaGapKinds : List TypeSchemaGapKind :=
  [.unknown_type]

/-- Every gap kind for TypeSchema is accounted for. -/
theorem TypeSchema_gap_kinds_complete :
    ∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds := by
  intro k
  cases k <;> simp [allTypeSchemaGapKinds]

/-- Gap statuses for TypeSchema formalism. -/
inductive TypeSchemaStatus where
  | absent
  | conforms
  | diverges
  deriving DecidableEq, Repr

/-- All statuses for TypeSchema. -/
def allTypeSchemaStatuses : List TypeSchemaStatus :=
  [.absent, .conforms, .diverges]

/-- Every status for TypeSchema is accounted for. -/
theorem TypeSchema_statuses_complete :
    ∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses := by
  intro s
  cases s <;> simp [allTypeSchemaStatuses]

/-- Monitor-schema consistency for TypeSchema: both gap-kind and status enumerations are exhaustive. -/
theorem TypeSchema_monitor_schema_consistent :
    (∀ k : TypeSchemaGapKind, k ∈ allTypeSchemaGapKinds) ∧
    (∀ s : TypeSchemaStatus, s ∈ allTypeSchemaStatuses) := by
  exact ⟨TypeSchema_gap_kinds_complete, TypeSchema_statuses_complete⟩

end StatechartMonitorSchema
