-- Generated by Pneuma system-level ->lean projection
-- Source: Statechart
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque HierarchyMap : Type := Unit
opaque InitialMap : Type := Unit
opaque KeywordSet : Type := Unit
opaque Statechart : Type := Unit
opaque TransitionVec : Type := Unit

inductive Op where
  | event_ids
  | raised_events
  | state_ids
  | statechart
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.event_ids, .raised_events, .state_ids, .statechart]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 4 := by
  rfl

def sc_api_dispatch : List Op :=
  [.statechart]

def sc_ref_kinds_dispatch : List Op :=
  [.event_ids, .raised_events, .state_ids]

-- Morphism api-caps->api-ops: sc_api dispatch ⊆ allOps [conforms]
theorem sc_api_dispatch_valid :
    ∀ op : Op, op ∈ sc_api_dispatch → op ∈ allOps := by
  decide

-- Morphism ref-kind-caps->ref-ops: sc_ref_kinds dispatch ⊆ allOps [conforms]
theorem sc_ref_kinds_dispatch_valid :
    ∀ op : Op, op ∈ sc_ref_kinds_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ sc_api_dispatch → op ∈ allOps) ∧
    (∀ op, op ∈ sc_ref_kinds_dispatch → op ∈ allOps) := by
  exact ⟨sc_api_dispatch_valid, sc_ref_kinds_dispatch_valid⟩
