namespace StructuralRefExhaustive

-- Ref-extraction exhaustiveness verification
-- Generated by Pneuma

-- Ref-extraction exhaustiveness for api

/-- Ref-kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureApi. -/
def allEffectSignatureApiRefKinds : List EffectSignatureApiRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureApi. -/
theorem EffectSignatureApi_ref_exhaustive :
    ∀ k : EffectSignatureApiRefKind, k ∈ allEffectSignatureApiRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiRefKinds]


-- Ref-extraction exhaustiveness for check

/-- Ref-kinds for EffectSignatureCheck formalism. -/
inductive EffectSignatureCheckRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureCheck. -/
def allEffectSignatureCheckRefKinds : List EffectSignatureCheckRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureCheck. -/
theorem EffectSignatureCheck_ref_exhaustive :
    ∀ k : EffectSignatureCheckRefKind, k ∈ allEffectSignatureCheckRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureCheckRefKinds]


-- Ref-extraction exhaustiveness for st-api

/-- Ref-kinds for CapabilitySetStApi formalism. -/
inductive CapabilitySetStApiRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetStApi. -/
def allCapabilitySetStApiRefKinds : List CapabilitySetStApiRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetStApi. -/
theorem CapabilitySetStApi_ref_exhaustive :
    ∀ k : CapabilitySetStApiRefKind, k ∈ allCapabilitySetStApiRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetStApiRefKinds]


-- Ref-extraction exhaustiveness for st-check

/-- Ref-kinds for CapabilitySetStCheck formalism. -/
inductive CapabilitySetStCheckRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetStCheck. -/
def allCapabilitySetStCheckRefKinds : List CapabilitySetStCheckRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetStCheck. -/
theorem CapabilitySetStCheck_ref_exhaustive :
    ∀ k : CapabilitySetStCheckRefKind, k ∈ allCapabilitySetStCheckRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetStCheckRefKinds]


-- Ref-extraction exhaustiveness for type-schema

/-- Ref-kinds for TypeSchema formalism. -/
inductive TypeSchemaRefKind where
  | type_ids
  deriving DecidableEq, Repr

/-- All ref-kinds for TypeSchema. -/
def allTypeSchemaRefKinds : List TypeSchemaRefKind :=
  [.type_ids]

/-- extract-refs handles every ref-kind for TypeSchema. -/
theorem TypeSchema_ref_exhaustive :
    ∀ k : TypeSchemaRefKind, k ∈ allTypeSchemaRefKinds := by
  intro k
  cases k <;> simp [allTypeSchemaRefKinds]

end StructuralRefExhaustive
