-- Generated by Pneuma system-level ->lean projection
-- Source: Structural
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque GapSeq : Type := Unit
opaque IProjectable : Type := Unit
opaque IReferenceable : Type := Unit
opaque Keyword : Type := Unit
opaque RefinementMap : Type := Unit
opaque StructuralMorphism : Type := Unit

inductive Op where
  | check
  | structural_morphism
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.check, .structural_morphism]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 2 := by
  rfl

def st_api_dispatch : List Op :=
  [.structural_morphism]

def st_check_dispatch : List Op :=
  [.check]

-- Morphism api-caps->api-ops: st_api dispatch ⊆ allOps [conforms]
theorem st_api_dispatch_valid :
    ∀ op : Op, op ∈ st_api_dispatch → op ∈ allOps := by
  decide

-- Morphism check-caps->check-ops: st_check dispatch ⊆ allOps [conforms]
theorem st_check_dispatch_valid :
    ∀ op : Op, op ∈ st_check_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ st_api_dispatch → op ∈ allOps) ∧
    (∀ op, op ∈ st_check_dispatch → op ∈ allOps) := by
  exact ⟨st_api_dispatch_valid, st_check_dispatch_valid⟩
