-- Generated by Pneuma system-level ->lean projection
-- Source: pneuma.protocol-spec
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque Formalism : Type := Unit
opaque GapSequence : Type := Unit
opaque GapTypeDesc : Type := Unit
opaque Generator : Type := Unit
opaque Keyword : Type := Unit
opaque KeywordSet : Type := Unit
opaque MalliSchema : Type := Unit
opaque MonitorFn : Type := Unit
opaque Morphism : Type := Unit
opaque RefinementMap : Type := Unit

inductive Op where
  | check
  | extract_refs
  | gap_type
  | gen
  | monitor
  | schema
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.check, .extract_refs, .gap_type, .gen, .monitor, .schema]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 6 := by
  rfl

def formalism_record_dispatch : List Op :=
  [.extract_refs, .gap_type, .gen, .monitor, .schema]

def morphism_record_dispatch : List Op :=
  [.check]

-- Morphism formalism-caps->ops: formalism_record dispatch ⊆ allOps [conforms]
theorem formalism_record_dispatch_valid :
    ∀ op : Op, op ∈ formalism_record_dispatch → op ∈ allOps := by
  decide

-- Morphism morphism-caps->ops: morphism_record dispatch ⊆ allOps [conforms]
theorem morphism_record_dispatch_valid :
    ∀ op : Op, op ∈ morphism_record_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ formalism_record_dispatch → op ∈ allOps) ∧
    (∀ op, op ∈ morphism_record_dispatch → op ∈ allOps) := by
  exact ⟨formalism_record_dispatch_valid, morphism_record_dispatch_valid⟩
