-- Generated by Pneuma system-level ->lean projection
-- Source: TypeSchema
-- Gap report: ALL CONFORMING
-- Proofs are mechanically generated from Pneuma's conformance check.
-- Conforming morphisms get `decide` proofs; failing ones get `sorry`.

opaque KeywordSet : Type := Unit
opaque TypeSchema : Type := Unit
opaque TypesMap : Type := Unit

inductive Op where
  | type_ids
  | type_schema
  deriving DecidableEq, Repr

def allOps : List Op :=
  [.type_ids, .type_schema]

theorem allOps_complete :
    ∀ op : Op, op ∈ allOps := by
  intro op
  cases op <;> simp [allOps]

theorem allOps_count :
    allOps.length = 2 := by
  rfl

def ts_api_dispatch : List Op :=
  [.type_schema]

def ts_ref_kinds_dispatch : List Op :=
  [.type_ids]

-- Morphism api-caps->api-ops: ts_api dispatch ⊆ allOps [conforms]
theorem ts_api_dispatch_valid :
    ∀ op : Op, op ∈ ts_api_dispatch → op ∈ allOps := by
  decide

-- Morphism ref-kind-caps->ref-ops: ts_ref_kinds dispatch ⊆ allOps [conforms]
theorem ts_ref_kinds_dispatch_valid :
    ∀ op : Op, op ∈ ts_ref_kinds_dispatch → op ∈ allOps := by
  decide

-- System-level: all capability dispatch sets reference valid operations
theorem system_conformance :
    (∀ op, op ∈ ts_api_dispatch → op ∈ allOps) ∧
    (∀ op, op ∈ ts_ref_kinds_dispatch → op ∈ allOps) := by
  exact ⟨ts_api_dispatch_valid, ts_ref_kinds_dispatch_valid⟩
