namespace TypeSchemaRefExhaustive

-- Ref-extraction exhaustiveness verification
-- Generated by Pneuma

-- Ref-extraction exhaustiveness for api

/-- Ref-kinds for EffectSignatureApi formalism. -/
inductive EffectSignatureApiRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureApi. -/
def allEffectSignatureApiRefKinds : List EffectSignatureApiRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureApi. -/
theorem EffectSignatureApi_ref_exhaustive :
    ∀ k : EffectSignatureApiRefKind, k ∈ allEffectSignatureApiRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureApiRefKinds]


-- Ref-extraction exhaustiveness for refs

/-- Ref-kinds for EffectSignatureRefs formalism. -/
inductive EffectSignatureRefsRefKind where
  | operation_ids
  | operation_outputs
  deriving DecidableEq, Repr

/-- All ref-kinds for EffectSignatureRefs. -/
def allEffectSignatureRefsRefKinds : List EffectSignatureRefsRefKind :=
  [.operation_ids, .operation_outputs]

/-- extract-refs handles every ref-kind for EffectSignatureRefs. -/
theorem EffectSignatureRefs_ref_exhaustive :
    ∀ k : EffectSignatureRefsRefKind, k ∈ allEffectSignatureRefsRefKinds := by
  intro k
  cases k <;> simp [allEffectSignatureRefsRefKinds]


-- Ref-extraction exhaustiveness for ts-api

/-- Ref-kinds for CapabilitySetTsApi formalism. -/
inductive CapabilitySetTsApiRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetTsApi. -/
def allCapabilitySetTsApiRefKinds : List CapabilitySetTsApiRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetTsApi. -/
theorem CapabilitySetTsApi_ref_exhaustive :
    ∀ k : CapabilitySetTsApiRefKind, k ∈ allCapabilitySetTsApiRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetTsApiRefKinds]


-- Ref-extraction exhaustiveness for ts-ref-kinds

/-- Ref-kinds for CapabilitySetTsRefKinds formalism. -/
inductive CapabilitySetTsRefKindsRefKind where
  | dispatch_refs
  deriving DecidableEq, Repr

/-- All ref-kinds for CapabilitySetTsRefKinds. -/
def allCapabilitySetTsRefKindsRefKinds : List CapabilitySetTsRefKindsRefKind :=
  [.dispatch_refs]

/-- extract-refs handles every ref-kind for CapabilitySetTsRefKinds. -/
theorem CapabilitySetTsRefKinds_ref_exhaustive :
    ∀ k : CapabilitySetTsRefKindsRefKind, k ∈ allCapabilitySetTsRefKindsRefKinds := by
  intro k
  cases k <;> simp [allCapabilitySetTsRefKindsRefKinds]


-- Ref-extraction exhaustiveness for type-schema

/-- Ref-kinds for TypeSchema formalism. -/
inductive TypeSchemaRefKind where
  | type_ids
  deriving DecidableEq, Repr

/-- All ref-kinds for TypeSchema. -/
def allTypeSchemaRefKinds : List TypeSchemaRefKind :=
  [.type_ids]

/-- extract-refs handles every ref-kind for TypeSchema. -/
theorem TypeSchema_ref_exhaustive :
    ∀ k : TypeSchemaRefKind, k ∈ allTypeSchemaRefKinds := by
  intro k
  cases k <;> simp [allTypeSchemaRefKinds]

end TypeSchemaRefExhaustive
