namespace TypeSchemaAlgebra

-- Morphism algebra for the specification graph
-- Generated by Pneuma

/-- Nodes of the morphism graph. Each node is a formalism kind. -/
inductive Node where
  | capability_set_ts_api
  | capability_set_ts_ref_kinds
  | effect_signature_api
  | effect_signature_refs
  | type_schema
  deriving DecidableEq, Repr

/-- All nodes in the morphism graph. -/
def allNodes : List Node :=
  [.capability_set_ts_api, .capability_set_ts_ref_kinds, .effect_signature_api, .effect_signature_refs, .type_schema]

/-- Every node appears in allNodes. -/
theorem allNodes_complete :
    ∀ n : Node, n ∈ allNodes := by
  intro n
  cases n <;> simp [allNodes]

/-- allNodes contains exactly 5 members. -/
theorem allNodes_count :
    allNodes.length = 5 := by
  rfl

/-- Edges of the morphism graph. Each edge is a morphism. -/
inductive Edge where
  | api_caps__api_ops
  | api_ops__types
  | ref_kind_caps__ref_ops
  | ref_ops__types
  deriving DecidableEq, Repr

/-- All edges in the morphism graph. -/
def allEdges : List Edge :=
  [.api_caps__api_ops, .api_ops__types, .ref_kind_caps__ref_ops, .ref_ops__types]

/-- Every edge appears in allEdges. -/
theorem allEdges_complete :
    ∀ e : Edge, e ∈ allEdges := by
  intro e
  cases e <;> simp [allEdges]

/-- Maps each edge to its source node. -/
def edgeSource : Edge → Node
  | .api_caps__api_ops => .capability_set_ts_api
  | .api_ops__types => .effect_signature_api
  | .ref_kind_caps__ref_ops => .capability_set_ts_ref_kinds
  | .ref_ops__types => .effect_signature_refs

/-- Maps each edge to its target node. -/
def edgeTarget : Edge → Node
  | .api_caps__api_ops => .effect_signature_api
  | .api_ops__types => .type_schema
  | .ref_kind_caps__ref_ops => .effect_signature_refs
  | .ref_ops__types => .type_schema

/-- Two edges are composable when the first's target equals the second's source. -/
def composable (e1 e2 : Edge) : Bool :=
  edgeTarget e1 == edgeSource e2

/-- Reflexivity: edgeSource and edgeTarget are well-defined for every edge. -/
theorem edge_endpoints_defined :
    ∀ e : Edge, edgeSource e ∈ allNodes ∧ edgeTarget e ∈ allNodes := by
  intro e
  cases e <;> simp [edgeSource, edgeTarget, allNodes]

/-- Composition associativity: if e1;e2 and e2;e3 compose, then grouping is irrelevant. -/
theorem composable_assoc :
    ∀ e1 e2 e3 : Edge,
      composable e1 e2 = true → composable e2 e3 = true →
      (edgeTarget e1 == edgeSource e2) = true ∧
      (edgeTarget e2 == edgeSource e3) = true := by
  decide

/-- Composable edges share a common interior node: target of e1 = source of e2. -/
theorem composable_shared_node :
    ∀ e1 e2 : Edge,
      composable e1 e2 = true →
      edgeTarget e1 = edgeSource e2 := by
  intro e1 e2 h
  simp [composable] at h
  exact beq_iff_eq.mp h

end TypeSchemaAlgebra
