(ns pneuma.code.render
    "Renders code fragment data into Clojure source strings and EDN.
  Converts the intermediate representation from ->code into files
  that can be written to disk."
    (:require [clojure.pprint :as pprint]
              [clojure.string :as str]))

;;; Form rendering

(defn- render-require
       "Renders a single require entry as a string."
       [req]
       (str req))

(defn- render-ns-form
       "Renders an ns form from a code fragment."
       [{:keys [namespace requires label]}]
       (let [req-strs (when (seq requires)
                            (str "\n    (:require "
                                 (str/join "\n              " (mapv render-require requires))
                                 ")"))]
            (str "(ns " namespace "\n"
                 "    \"Generated by Pneuma from " label ".\n"
                 "  DO NOT EDIT — all business logic goes in the fills namespace.\""
                 (or req-strs "")
                 ")\n")))

(defn- render-defmulti
       "Renders a defmulti form."
       [{:keys [name dispatch doc]}]
       (str "\n(defmulti " name "\n"
            "          \"" doc "\"\n"
            "          " dispatch ")\n"))

(defn- render-defmethod-comment
       "Renders the comment for a defmethod."
       [{:keys [comment]}]
       (when comment
             (str "\n;; " comment)))

(defn- render-defmethod-statechart
       "Renders a statechart defmethod form."
       [{:keys [dispatch-val target guard fills effects] :as form}]
       (str (render-defmethod-comment form) "\n"
            "(defmethod handle-event " dispatch-val "\n"
            "  [db {:keys [session-id] :as event}]\n"
            (when (seq guard)
                  (str "  {:pre [" (str/join "\n         " (mapv str guard)) "]}\n"))
            "  (let [db' (-> db\n"
            "               (state/set-conv-state session-id " target ")\n"
            (str/join ""
                      (mapv (fn [fp]
                                (str "               (fill " (:key fp) " "
                                     (str/join " " (:args fp)) ")\n"))
                            fills))
            "               )]\n"
            "    {:db db'\n"
            "     :effects [" (str/join " " (mapv str (or effects []))) "]}))\n"))

(defn- render-defmethod-effect
       "Renders an effect executor defmethod form."
       [{:keys [dispatch-val destructure fills] :as form}]
       (str (render-defmethod-comment form) "\n"
            "(defmethod execute-effect " dispatch-val "\n"
            "  [{:keys [" (str/join " " (mapv name destructure)) "] :as effect}]\n"
            "  (fill " (:key (first fills)) " "
            (str/join " " (:args (first fills))) "))\n"))

(defn- render-defmethod-mealy
       "Renders a mealy handler defmethod form."
       [{:keys [dispatch-val params fills] :as form}]
       (let [param-names (mapv (comp name :name) params)]
            (str (render-defmethod-comment form) "\n"
                 "(defmethod handle-event " dispatch-val "\n"
                 "  [db {:keys [" (str/join " " param-names) "] :as event}]\n"
                 (str/join ""
                           (mapv (fn [fp]
                                     (str "  (fill " (:key fp) " "
                                          (str/join " " (:args fp)) ")\n"))
                                 fills))
                 ")\n")))

(defn- render-subscription
       "Renders a subscription declaration."
       [{:keys [optic-id optic-type path sources fills] :as form}]
       (str (render-defmethod-comment form) "\n"
            ";; " (name optic-type) " " optic-id
            (when path (str " path: " path)) "\n"
            (if (= :Derived optic-type)
                (str "(reg-sub " optic-id "\n"
                     "  :sources " sources "\n"
                     "  :compute (fn [sources]\n"
                     "             (fill " (:key (first fills)) " sources)))\n")
                (str "(reg-sub " optic-id "\n"
                     "  :path " path ")\n"))))

(defn- render-resolver
       "Renders a resolver declaration."
       [{:keys [resolver-id input output source fills] :as form}]
       (str (render-defmethod-comment form) "\n"
            "(defresolver " resolver-id "\n"
            "  {:input  " input "\n"
            "   :output " output
            (when source (str "\n   :source " source)) "}\n"
            "  (fn [env " (str/join " " (mapv (comp name :name) [])) "]\n"
            "    (fill " (:key (first fills)) " env)))\n"))

(defn- render-guard-check
       "Renders a capability guard check."
       [{:keys [capability-id kind allowed] :as form}]
       (str (render-defmethod-comment form) "\n"
            "(def " (name capability-id) "-" (name kind) "-guard\n"
            "  \"Allowed " (name kind) " operations for " (name capability-id) ".\"\n"
            "  " (pr-str allowed) ")\n"))

(defn render-form
      "Renders a single form to a Clojure source string."
      [form]
      (case (:type form)
            :defmulti (render-defmulti form)
            :defmethod (cond
                        (:source form) (render-defmethod-statechart form)
                        (:destructure form) (render-defmethod-effect form)
                        :else (render-defmethod-mealy form))
            :subscription (render-subscription form)
            :resolver (render-resolver form)
            :guard-check (render-guard-check form)
            (str ";; Unknown form type: " (:type form) "\n")))

;;; File rendering

(defn render-source
      "Renders a complete code fragment to a Clojure source string."
      [code-fragment]
      (str (render-ns-form code-fragment)
           (str/join "" (mapv render-form (:forms code-fragment)))))

(defn render-manifest
      "Renders a fill manifest to an EDN string."
      [manifest]
      (with-out-str
       (binding [*print-namespace-maps* false]
                (pprint/pprint manifest))))

(defn render-fills-skeleton
      "Renders a skeleton fills namespace for fill points that need
  human implementation."
      [target-ns manifest]
      (let [fills-ns (symbol (str target-ns ".fills"))]
           (str "(ns " fills-ns "\n"
                "    \"Human-written fill implementations.\n"
                "  This file is NEVER regenerated by Pneuma.\"\n"
                "    (:require [pneuma.fills :refer [reg-fill]]))\n"
                (str/join ""
                          (mapv (fn [[k {:keys [args returns doc]}]]
                                    (str "\n;; " (or doc (name k)) "\n"
                                         ";; Args: " args " → " returns "\n"
                                         "(reg-fill " k "\n"
                                         "  (fn " (vec args) "\n"
                                         "    (throw (ex-info \"TODO: implement " k "\" {}))))\n"))
                                (sort-by key manifest))))))
